'use client';import {useState} from 'react';import {Check,CheckCircle2,LoaderCircle,X} from 'lucide-react';import {Meeting} from '@/lib/types';
export function StatusBadge({status}:{status:Meeting['status']}){const names={uploaded:'Ready to process',processing:'Processing',completed:'Completed',failed:'Failed'};return <span className={`badge ${status==='completed'?'badge-green':status==='failed'?'badge-amber':''}`}>{status==='processing'&&<LoaderCircle size={11} className="spin"/>}{names[status]}</span>}
export function Toast({message,onClose}:{message:string|null;onClose:()=>void}){if(!message)return null;return <div className="toast" onClick={onClose}>{message}</div>}
export function Modal({children,onClose,title}:{children:React.ReactNode;onClose:()=>void;title:string}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modal-head"><div className="section-title">{title}</div><button className="btn btn-sm" onClick={onClose}><X size={14}/></button></div>{children}</div></div>}
export function ProcessingView({meeting,onRetry}:{meeting:Meeting;onRetry:()=>void}){
 const stages=meeting.inputType==='notes'?['Analyzing meeting and identifying tasks','Generating ticket drafts','Complete']:['Transcribing','Analyzing meeting and identifying tasks','Generating ticket drafts','Complete'];
 const stageIndex=stages.indexOf(meeting.stage||'');
 const activity=meeting.status==='failed'?'Review the error below, then retry processing.':meeting.stage==='Transcribing'?'Preparing the recording and converting speech to text.':meeting.stage==='Analyzing meeting and identifying tasks'?'Reading the transcript and identifying meeting decisions and agreed work.':meeting.stage==='Generating ticket drafts'?'Turning confirmed work items into ticket drafts.':'Getting the meeting ready for processing.';
 const diagnosticLabel=meeting.stage==='Transcribing'?'TRANSCRIPTION DETAILS':meeting.stage==='Analyzing meeting and identifying tasks'?'MEETING ANALYSIS DETAILS':meeting.stage==='Generating ticket drafts'?'TICKET DRAFTING DETAILS':'PROCESSING DETAILS';
 return <div className="page"><div className="progress-wrap"><div className="eyebrow">MEETING PROCESSING</div><h1 className="page-title">{meeting.status==='failed'?'Processing stopped':meeting.inputType==='notes'?'Turning your meeting notes into tickets':'Turning your recording into tickets'}</h1><p className="subtle">{meeting.status==='failed'?'Something interrupted this meeting. Review the error and retry.':`Working on ${meeting.title}`}</p><div className="card" style={{padding:20,marginTop:24}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,fontWeight:600}}><span>{meeting.status==='processing'?'Current step: ':''}{meeting.stage||'Starting'}</span><span style={{color:'#89928d'}}>{meeting.progress}%</span></div><div className="progress-track"><div className="progress-fill" style={{width:`${meeting.progress}%`}}/></div><div className="stage-list">{stages.map((s,i)=><div className={`stage-row ${i===stageIndex?'active':''} ${i<stageIndex?'done':''}`} key={s}><span className="stage-icon">{i<stageIndex?<CheckCircle2 size={15}/>:i===stageIndex&&meeting.status==='processing'?<LoaderCircle size={15}/>:<span style={{border:'1px solid #ccd4ce',width:14,height:14,borderRadius:'50'}}/>}</span>{s}</div>)}</div><div role="status" aria-live="polite" style={{marginTop:17,padding:'12px 14px',borderRadius:6,background:'#f3f7f4',color:'#344b3d',fontSize:12,lineHeight:1.6}}><div className="eyebrow" style={{fontSize:9,marginBottom:4}}>WHAT'S HAPPENING · {diagnosticLabel}</div>{activity}{meeting.diagnostic&&meeting.status==='processing'&&<div className="subtle" style={{fontSize:11,marginTop:4}}>{meeting.diagnostic}</div>}</div>{meeting.error&&<div className="error-box">{meeting.error}</div>}{meeting.status==='failed'&&<button className="btn btn-primary" style={{marginTop:14}} onClick={onRetry}>Retry processing</button>}</div><p className="muted" style={{marginTop:14}}>You can safely leave this page. Processing status is saved with the meeting.</p></div></div>
}
