import {describe,expect,it} from 'vitest';
import {resolveAssignment} from './assignment';
import {AssignmentRule,ProjectProfile} from './types';
import {randomUUID} from 'node:crypto';

function setup(){const surfaceId=randomUUID(),componentId=randomUUID(),areaId=randomUUID(),typeId=randomUUID(),johnId=randomUUID(),sarahId=randomUUID();const profile:ProjectProfile={id:randomUUID(),name:'Payments',description:'',instructions:'',glossary:{},taskTypes:[{id:typeId,name:'Backend',description:'',position:0}],surfaces:[{id:surfaceId,name:'Payments API',description:'',components:[{id:componentId,name:'Checkout',description:''}]}],workAreas:[{id:areaId,name:'Backend',description:''}],members:[{id:johnId,name:'John Smith',role:'Backend engineer',skills:['Payments','Node.js'],responsibilities:['Payments backend'],areaIds:[areaId],componentIds:[componentId],aliases:['John'],email:null,externalId:null,active:true},{id:sarahId,name:'Sarah',role:'Frontend engineer',skills:['React'],responsibilities:['Dashboard UI'],areaIds:[],componentIds:[],aliases:[],email:null,externalId:null,active:true}],assignmentRules:[],documents:[],createdAt:'',updatedAt:''};const task={title:'Fix payment timeout in checkout',description:'Repair timeout handling in the payments API',type:'Backend',surface:'Payments API',area:'Backend',component:'Checkout',assignee:null,assignmentEvidence:'none' as const};return{profile,task,johnId,sarahId,surfaceId,componentId,areaId,typeId}}
describe('assignment resolution',()=>{
 it('prefers an explicit meeting assignment over matching rules',()=>{const x=setup();x.profile.assignmentRules=[{id:randomUUID(),name:'Payments backend to Sarah',surfaceId:x.surfaceId,componentId:x.componentId,areaId:x.areaId,taskTypeId:x.typeId,memberId:x.sarahId,active:true,position:0}];const result=resolveAssignment({...x.task,assignee:'John',assignmentEvidence:'explicit'},x.profile);expect(result.assigneeId).toBe(x.johnId);expect(result.source).toBe('meeting');expect(result.needsReview).toBe(false)});
 it('applies explicit project assignment rules before skills and ownership',()=>{const x=setup();x.profile.assignmentRules=[{id:randomUUID(),name:'Payments backend to Sarah',surfaceId:x.surfaceId,componentId:x.componentId,areaId:x.areaId,taskTypeId:x.typeId,memberId:x.sarahId,active:true,position:0}];const result=resolveAssignment(x.task,x.profile);expect(result.assigneeId).toBe(x.sarahId);expect(result.source).toBe('rule')});
 it('uses responsibility matches before skills',()=>{const x=setup();x.profile.assignmentRules=[];const result=resolveAssignment(x.task,x.profile);expect(result.assigneeId).toBe(x.johnId);expect(result.source).toBe('responsibility')});
 it('does not assign an unknown explicit meeting name',()=>{const x=setup();const result=resolveAssignment({...x.task,assignee:'Jordan',assignmentEvidence:'explicit'},x.profile);expect(result.assigneeId).toBeNull();expect(result.needsReview).toBe(true);expect(result.source).toBe('unassigned')});
 it('does not invent an assignee when no project roster exists',()=>{const x=setup();const result=resolveAssignment({...x.task,assignee:'John',assignmentEvidence:'recommendation'},null);expect(result.assigneeId).toBeNull();expect(result.needsReview).toBe(true)});
 it('marks conflicting equally specific rules for review',()=>{const x=setup();const rule=(memberId:string,position:number):AssignmentRule=>({id:randomUUID(),name:'Rule',surfaceId:x.surfaceId,componentId:null,areaId:x.areaId,taskTypeId:null,memberId,active:true,position});x.profile.assignmentRules=[rule(x.johnId,0),rule(x.sarahId,0)];const result=resolveAssignment(x.task,x.profile);expect(result.assigneeId).toBeNull();expect(result.needsReview).toBe(true)});
});
