import {describe,expect,it} from 'vitest';
import {extractDocument,normalizeDocumentText,validateDocumentFilename} from './knowledge';

const projectId='project-test',documentId='document-test',versionId='version-test';
function tinyPdf(pages:string[]){const objects:string[]=['<< /Type /Catalog /Pages 2 0 R >>',`<< /Type /Pages /Kids [${pages.map((_,i)=>`${i*2+3} 0 R`).join(' ')}] /Count ${pages.length} >>`];pages.forEach((text,index)=>{const pageId=index*2+3;objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${pages.length*2+3} 0 R >> >> /Contents ${pageId+1} 0 R >>`);const stream=`BT /F1 18 Tf 72 720 Td (${text}) Tj ET`;objects.push(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`)});objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((object,index)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(const offset of offsets.slice(1))pdf+=`${String(offset).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Uint8Array(Buffer.from(pdf))}

describe('project document extraction and chunking',()=>{
 it('validates paths and supported document types',()=>{expect(validateDocumentFilename('spec.pdf').type).toBe('application/pdf');expect(()=>validateDocumentFilename('../secrets.txt')).toThrow(/filename/);expect(()=>validateDocumentFilename('archive.xml')).toThrow(/Unsupported/)});
 it('normalizes text encodings, BOM, and line endings before chunking',async()=>{expect(normalizeDocumentText('\uFEFFA\r\nB\rC\u0000')).toBe('A\nB\nC');const result=await extractDocument(new TextEncoder().encode('\uFEFF# Intro\r\n\r\nReadable text.'),'guide.md',projectId,documentId,versionId);expect(result.metadata.encoding).toBe('utf-8');expect(result.chunks[0].text).toContain('Readable text.');expect(result.chunks[0].chunkId).toBeTruthy()});
 it('extracts PDF text with page numbers and page metadata',async()=>{const result=await extractDocument(tinyPdf(['Payments endpoint details','Dashboard page details']),'architecture.pdf',projectId,documentId,versionId);expect(result.metadata.pageCount).toBe(2);expect(result.chunks.map(chunk=>chunk.pageNumber)).toEqual([1,2]);expect(result.chunks[0].text).toContain('Payments endpoint details')});
 it('marks image-only PDFs as requiring OCR rather than extracting empty text',async()=>{await expect(extractDocument(tinyPdf(['']), 'scan.pdf',projectId,documentId,versionId)).rejects.toThrow(/OCR/)});
 it('parses quoted CSV fields, comma values, empty cells, UTF-8, and line endings',async()=>{const csv='name,role,responsibility,notes\r\nJohn,"Backend Developer","Payments API","handles, retries"\r\nSarah,Frontend Developer,"Dashboard UI",\r\nZoë,Engineer,API,"line one\nline two"';const result=await extractDocument(new TextEncoder().encode(csv),'team.csv',projectId,documentId,versionId);expect(result.metadata).toMatchObject({rowCount:3,columnCount:4,columns:['name','role','responsibility','notes']});expect(result.chunks.some(chunk=>chunk.text.includes('name: John | role: Backend Developer | responsibility: Payments API | notes: handles, retries'))).toBe(true);expect(result.chunks.find(chunk=>chunk.text.includes('name: Sarah'))?.rowNumber).toBe(3);expect(result.chunks.some(chunk=>chunk.text.includes('name: Zoë'))).toBe(true)});
 it('rejects malformed JSON and non-UTF-8 text during extraction',async()=>{await expect(extractDocument(new TextEncoder().encode('{oops'),'broken.json',projectId,documentId,versionId)).rejects.toThrow(/JSON/);await expect(extractDocument(new Uint8Array([0xff,0xfe]),'broken.txt',projectId,documentId,versionId)).rejects.toThrow(/UTF-8/)});
});
