import {Analysis} from './types';import {getSelectedModel} from './model-settings';import {analysisSchema} from './validation';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
const execFileAsync=promisify(execFile);
async function transcribeLocal(file:File):Promise<string>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'meeting-whisper-'));const safeName=file.name.replace(/[^\w.-]/g,'_')||'recording';const input=path.join(dir,safeName);const audio=path.join(dir,'normalized.wav');
 try{await writeFile(input,Buffer.from(await file.arrayBuffer()));try{await execFileAsync(process.env.FFMPEG_BIN||'ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y','-i',input,'-vn','-ac','1','-ar','16000','-c:a','pcm_s16le',audio],{timeout:Number(process.env.FFMPEG_TIMEOUT_MS||900000),maxBuffer:4*1024*1024})}catch(e){const message=e instanceof Error?e.message:'FFmpeg failed';throw new Error(`Could not prepare meeting audio: ${message}. Confirm FFmpeg is installed and the recording is readable.`)}
  const binary=(process.env.WHISPER_BIN||path.join(os.homedir(),'.local/bin/whisper-cli')).replace(/^~(?=\/)/,os.homedir());const model=(process.env.WHISPER_MODEL||'small').trim();const modelPath=(process.env.WHISPER_MODEL_PATH||path.join(os.homedir(),'.local/share/meeting-to-tickets',`ggml-${model}.bin`)).replace(/^~(?=\/)/,os.homedir());const output=path.join(dir,'transcript');const args=['-m',modelPath,'-f',audio,'-oj','-np','-of',output,'-t',process.env.WHISPER_THREADS||'4'];if(process.env.WHISPER_USE_GPU==='false')args.push('-ng');
  try{await execFileAsync(binary,args,{timeout:Number(process.env.WHISPER_TIMEOUT_MS||2700000),maxBuffer:4*1024*1024,env:{...process.env,LD_LIBRARY_PATH:[process.env.LD_LIBRARY_PATH,path.join(os.homedir(),'.local/lib')].filter(Boolean).join(path.delimiter)}})}catch(e){const message=e instanceof Error?e.message:'Whisper failed';throw new Error(`GPU Whisper transcription failed: ${message}. Check that whisper.cpp was built with Vulkan and that ggml-small.bin is installed.`)}
  const result=JSON.parse(await readFile(`${output}.json`,'utf8'));if(Array.isArray(result.transcription)&&result.transcription.length)return result.transcription.map((segment:{offsets?:{from?:number};timestamps?:{from?:string};text:string})=>{const ms=segment.offsets?.from??0;const seconds=Math.floor(ms/1000);const stamp=segment.timestamps?.from?.slice(0,5)??`${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`;return `[${stamp}] ${segment.text.trim()}`}).join('\n');return String(result.text||'')
 }finally{await rm(dir,{recursive:true,force:true})}
}
export async function transcribe(file:File):Promise<string>{
 const provider=process.env.AI_PROVIDER||'ollama';
 if(provider==='demo'){await new Promise(r=>setTimeout(r,1400));return 'Alex: We need to address a bug where payment callbacks fail when transactions time out.\n\nPriya: Let’s add retry handling with a limit and log each failed attempt. Alex, can you take that?\n\nAlex: Yes, I’ll implement the retry logic and make sure duplicate callbacks do not create duplicate transactions.\n\nPriya: We should also update the payment API documentation after the behavior is finalized.'}
 if(provider==='ollama')return transcribeLocal(file);
 if(provider!=='openai')throw new Error(`Unsupported AI_PROVIDER: ${provider}`);
 const key=process.env.OPENAI_API_KEY;if(!key)throw new Error('OPENAI_API_KEY is missing. Set AI_PROVIDER=ollama to use local models.');
 const body=new FormData();body.set('file',file,file.name);body.set('model',process.env.OPENAI_TRANSCRIPTION_MODEL||'whisper-1');body.set('response_format','verbose_json');
 const res=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{Authorization:`Bearer ${key}`},body});if(!res.ok)throw new Error(`Transcription provider error (${res.status}): ${await res.text()}`);const result=await res.json();if(Array.isArray(result.segments)&&result.segments.length)return result.segments.map((s:{start:number;text:string})=>`[${Math.floor(s.start/60).toString().padStart(2,'0')}:${Math.floor(s.start%60).toString().padStart(2,'0')}] ${s.text.trim()}`).join('\n');return String(result.text||'');
}
export async function analyze(transcript:string,context:string|null,meetingTitle:string,selectedModel?:string):Promise<Analysis>{
 const provider=process.env.AI_PROVIDER||'ollama';
 if(provider==='demo'){await new Promise(r=>setTimeout(r,1000));return analysisSchema.parse({summary:'The team discussed a timeout-related payment callback bug and agreed to implement bounded retries, failure logging, and duplicate prevention. The payment API documentation will be updated after the behavior is finalized.',topics:['Payment callbacks','Transaction timeouts','API documentation'],decisions:['Add bounded retry handling for failed payment callbacks.','Prevent duplicate transactions from duplicate callbacks.','Log failed callback attempts.'],taskCandidates:[{intent:'committed',title:'Add retry handling for payment callbacks',description:'Implement bounded retries for failed payment callbacks when transactions time out, and prevent duplicate callbacks from creating duplicate transactions.',type:'bug',priority:'high',assignee:'Alex',deadline:null,context:'Payment callbacks fail on transaction timeouts.',sourceTimestamp:null,acceptanceCriteria:['Retry failed callbacks with a defined limit.','Log each failed attempt.','Duplicate callbacks do not create duplicate transactions.'],sourceQuote:'Let’s add retry handling with a limit and log each failed attempt. Alex, can you take that? Yes, I’ll implement the retry logic and make sure duplicate callbacks do not create duplicate transactions.',confidence:0.96},{intent:'committed',title:'Update payment API documentation',description:'Update the payment API documentation to reflect the finalized callback behavior.',type:'improvement',priority:'medium',assignee:null,deadline:null,context:'Payment API documentation should be updated after callback behavior is finalized.',sourceTimestamp:null,acceptanceCriteria:['Document the finalized payment callback behavior.'],sourceQuote:'We should also update the payment API documentation after the behavior is finalized.',confidence:0.83}]})}
 const instructions=`Analyze software meeting material, which may be a transcript or notes. Return ONLY JSON matching: {summary:string,topics:string[],decisions:string[],taskCandidates:[{intent:"committed"|"proposed"|"rejected"|"cancelled"|"deferred"|"unclear",title,description,type:"feature"|"bug"|"improvement"|"technical-task"|"research",priority:"low"|"medium"|"high",assignee:string|null,deadline:string|null,context:string,sourceTimestamp:string|null,acceptanceCriteria:string[],sourceQuote:string,confidence:number}]}. Classify each committed work item as bug, feature, or task (use bug for defects, feature for new capability, technical-task/improvement/research for other work). For each possible task, determine its FINAL intent from the whole discussion before drafting it. Use committed only when the work is clearly agreed, assigned and accepted, or explicitly confirmed as work to do. Use proposed for suggestions/questions that are not accepted. Use rejected or cancelled when the group declines, withdraws, or says not to do the work. Use deferred when they explicitly postpone it without committing to do it now. Use unclear when commitment cannot be established. A later rejection/cancellation overrides an earlier suggestion or apparent agreement; never turn rejected, cancelled, deferred, proposed, or unclear items into committed work. Example: “We should add profile status posts. No, let’s not; it’s unnecessary.” => candidate intent rejected, no ticket draft; mention the rejection as a decision when relevant. Don't interpret discussion of an existing problem as authorization to fix it unless the meeting commits to work. Do not invent requirements, deadlines, or assignees; use null if none was stated and medium if priority is unclear. Set deadline only when an explicit deadline/date is stated; otherwise null. Set context to concise surrounding context needed to understand this item. Set sourceTimestamp only when the transcript has a timestamp for the supporting passage, copied exactly; for notes without timestamps use null. Include a short verbatim quote from the provided meeting material supporting both the proposed work and, when applicable, its final acceptance/rejection. Prefer fewer high-quality candidates. Context may clarify terms but is not evidence of commitment. The source may be concise or fragmentary notes; interpret them with the additional context while keeping commitment evidence grounded in the provided material. Meeting title: ${meetingTitle}\nAdditional context: ${context||'None'}`;
 let payload:any;
 if(provider==='ollama'){
  const base=(process.env.OLLAMA_BASE_URL||'http://localhost:11434').replace(/\/$/,'');let response:Response;try{response=await fetch(`${base}/api/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:selectedModel||await getSelectedModel(),stream:false,think:false,format:'json',options:{temperature:0.1,num_ctx:Number(process.env.OLLAMA_NUM_CTX||8192),num_gpu:999},messages:[{role:'system',content:instructions},{role:'user',content:transcript}]})})}catch{throw new Error(`Cannot connect to Ollama at ${base}. Start Ollama and confirm the model is available.`)}if(!response.ok)throw new Error(`Ollama analysis error (${response.status}): ${await response.text()}`);const result=await response.json();const content=result.message?.content;if(!content)throw new Error('Ollama returned an empty response.');try{payload=JSON.parse(content)}catch{throw new Error('Ollama model returned invalid JSON. Please retry.')}
 }else if(provider==='openai'){
  const key=process.env.OPENAI_API_KEY;if(!key)throw new Error('OPENAI_API_KEY is missing. Set AI_PROVIDER=ollama to use local models.');const res=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_ANALYSIS_MODEL||'gpt-4o-mini',temperature:0.1,response_format:{type:'json_object'},messages:[{role:'system',content:instructions},{role:'user',content:transcript}]})});if(!res.ok)throw new Error(`Analysis provider error (${res.status}): ${await res.text()}`);const content=(await res.json()).choices?.[0]?.message?.content;if(!content)throw new Error('Analysis provider returned an empty response.');try{payload=JSON.parse(content)}catch{throw new Error('Analysis provider returned invalid JSON. Please retry.')}
 }else throw new Error(`Unsupported AI_PROVIDER: ${provider}`);
 return analysisSchema.parse(payload);
}
