import Database from 'better-sqlite3';
import {createHash,randomUUID} from 'node:crypto';
import {existsSync,mkdirSync,readFileSync,renameSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {DocumentExtractMetadata,Meeting,MeetingTaskEvidence,Priority,ProjectDocument,ProjectKnowledgeChunk,ProjectProfile,ProjectSnapshot,ProjectReferenceEvidence,SpeakerMapping,Task,TaskCandidate,TaskReviewStatus,Ticket,TicketStatus,TranscriptSegment,UpdateTicketInput} from './types';
import {ProjectProfileInput} from './validation';
import {extractDocument,MAX_DOCUMENT_BYTES,validateDocumentFilename} from './knowledge';
import {logger} from './logger';

export interface Storage {
 listMeetings():Promise<Meeting[]>;getMeeting(id:string):Promise<{meeting:Meeting|null;tasks:Task[];candidates:TaskCandidate[];tickets:Ticket[]}>;saveMeeting(meeting:Meeting):Promise<Meeting>;
 addTasks(tasks:Task[]):Promise<void>;saveTask(task:Task):Promise<Task>;saveCandidates(meetingId:string,candidates:TaskCandidate[]):Promise<void>;deleteTask(id:string):Promise<void>;getTask(id:string):Promise<Task|null>;
 saveTicket(ticket:Ticket):Promise<Ticket>;getTicket(id:string):Promise<Ticket|null>;findTicketBySourceTaskId(sourceTaskId:string):Promise<Ticket|null>;listTickets(filter?:{projectId?:string;meetingId?:string;status?:string}):Promise<Ticket[]>;updateTicket(id:string,patch:UpdateTicketInput):Promise<Ticket>;deleteTicket(id:string):Promise<void>;
 listProjects():Promise<ProjectProfile[]>;getProject(id:string):Promise<ProjectProfile|null>;saveProject(profile:ProjectProfileInput&{id:string;createdAt?:string;updatedAt?:string}):Promise<ProjectProfile>;deleteProject(id:string):Promise<void>;
 ingestProjectDocument(projectId:string,filename:string,bytes:Uint8Array):Promise<ProjectDocument>;deleteProjectDocument(projectId:string,documentId:string):Promise<void>;reprocessProjectDocument(projectId:string,documentId:string):Promise<ProjectDocument>;searchProjectKnowledge(projectId:string,query:string,limit?:number,versionIds?:string[]):Promise<ProjectKnowledgeChunk[]>;
 hydrateProjectSnapshot(snapshot:ProjectSnapshot|null):Promise<ProjectSnapshot|null>;close():void;
 getSpeakerMappings(meetingId:string):SpeakerMapping[];
 setSpeakerMapping(meetingId:string,speakerId:string,memberId:string|null):SpeakerMapping[];
}


type SqliteOptions={dataDir?:string;legacyDataDir?:string};
// Raw SQLite rows are validated and mapped at this storage boundary.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row=Record<string,any>;
const now=()=>new Date().toISOString();
const json=<T>(value:unknown,fallback:T):T=>{try{return value==null?fallback:JSON.parse(String(value)) as T}catch{return fallback}};
const hash=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex');

export class SqliteStorage implements Storage{
 readonly db:Database.Database;readonly dataDir:string;readonly legacyDataDir:string;readonly documentsDir:string;
 constructor(filename:string,options:SqliteOptions={}){this.dataDir=options.dataDir||path.dirname(filename);this.legacyDataDir=options.legacyDataDir||this.dataDir;this.documentsDir=path.join(this.dataDir,'project-documents');mkdirSync(this.dataDir,{recursive:true});mkdirSync(this.documentsDir,{recursive:true});this.db=new Database(filename);this.db.pragma('foreign_keys = ON');this.db.pragma('journal_mode = WAL');this.db.pragma('busy_timeout = 5000');this.db.exec(SCHEMA);this.ensureColumn('meetings','open_questions_json',"TEXT NOT NULL DEFAULT '[]'");this.ensureColumn('meetings','diarization_status',"TEXT DEFAULT 'not_started'");this.ensureColumn('meetings','diarization_error','TEXT');this.ensureColumn('meetings','speaker_count','INTEGER');this.ensureColumn('meetings','speaker_mappings_json',"TEXT DEFAULT '{}'");this.ensureColumn('transcript_segments','speaker_id','TEXT');this.ensureColumn('transcript_segments','speaker_confidence','REAL');this.ensureColumn('tickets','rejection_reason','TEXT');this.ensureColumn('tickets','created_ticket_id','TEXT');this.migrateDocumentStatusCheck();this.migrateLegacyData();this.migrateDiarizationSchema();this.flagDocumentsNeedingIndexing()}

 listMeetings(){const rows=this.db.prepare('SELECT * FROM meetings ORDER BY created_at DESC').all() as Row[];return Promise.resolve(rows.map(r=>this.meetingFromRow(r)))}
 getMeeting(id:string){const row=this.db.prepare('SELECT * FROM meetings WHERE id=?').get(id) as Row|undefined;const candidates=(this.db.prepare('SELECT * FROM task_candidates WHERE meeting_id=? ORDER BY created_at,id').all(id) as Row[]).map(row=>({id:row.id,meetingId:row.meeting_id,intent:row.intent,payload:json<Record<string,unknown>>(row.payload_json,{}),createdAt:row.created_at}) as TaskCandidate);return Promise.resolve({meeting:row?this.meetingFromRow(row):null,tasks:this.tasksForMeeting(id),candidates,tickets:this.ticketsForMeeting(id)})}
 saveMeeting(meeting:Meeting){const old=this.db.prepare('SELECT transcript FROM meetings WHERE id=?').get(meeting.id) as Row|undefined;const snapshot=meeting.projectSnapshot?stripSnapshotContent(meeting.projectSnapshot):null;const mappingsObj:Record<string,string>={};if(meeting.speakerMappings)for(const m of meeting.speakerMappings)mappingsObj[m.speakerId]=m.memberId;const insert=this.db.prepare(`INSERT INTO meetings(id,input_type,title,meeting_type,context,project_id,project_snapshot_json,original_file_name,file_url,file_size,duration,status,stage,progress,error,diagnostic,transcript,summary,topics_json,decisions_json,open_questions_json,diarization_status,diarization_error,speaker_count,speaker_mappings_json,created_at,updated_at) VALUES(@id,@inputType,@title,@meetingType,@context,@projectId,@snapshot,@originalFileName,@fileUrl,@fileSize,@duration,@status,@stage,@progress,@error,@diagnostic,@transcript,@summary,@topics,@decisions,@openQuestions,@diarizationStatus,@diarizationError,@speakerCount,@speakerMappingsJson,@createdAt,@updatedAt) ON CONFLICT(id) DO UPDATE SET input_type=excluded.input_type,title=excluded.title,meeting_type=excluded.meeting_type,context=excluded.context,project_id=excluded.project_id,project_snapshot_json=excluded.project_snapshot_json,original_file_name=excluded.original_file_name,file_url=excluded.file_url,file_size=excluded.file_size,duration=excluded.duration,status=excluded.status,stage=excluded.stage,progress=excluded.progress,error=excluded.error,diagnostic=excluded.diagnostic,transcript=excluded.transcript,summary=excluded.summary,topics_json=excluded.topics_json,decisions_json=excluded.decisions_json,open_questions_json=excluded.open_questions_json,diarization_status=excluded.diarization_status,diarization_error=excluded.diarization_error,speaker_count=excluded.speaker_count,speaker_mappings_json=excluded.speaker_mappings_json,updated_at=excluded.updated_at`);
  const txn=this.db.transaction(()=>{insert.run({id:meeting.id,inputType:meeting.inputType,title:meeting.title,meetingType:meeting.meetingType,context:meeting.context,projectId:meeting.projectId,snapshot:JSON.stringify(snapshot),originalFileName:meeting.originalFileName,fileUrl:meeting.fileUrl,fileSize:meeting.fileSize,duration:meeting.duration,status:meeting.status,stage:meeting.stage,progress:meeting.progress,error:meeting.error,diagnostic:meeting.diagnostic,transcript:meeting.transcript,summary:meeting.summary,topics:JSON.stringify(meeting.topics),decisions:JSON.stringify(meeting.decisions),openQuestions:JSON.stringify(meeting.openQuestions||[]),diarizationStatus:meeting.diarizationStatus||'not_started',diarizationError:meeting.diarizationError||null,speakerCount:meeting.speakerCount??null,speakerMappingsJson:JSON.stringify(mappingsObj),createdAt:meeting.createdAt,updatedAt:meeting.updatedAt});if(old?.transcript!==meeting.transcript||(meeting.transcriptSegments&&meeting.transcriptSegments.length>0))this.replaceTranscriptSegments(meeting);if(meeting.speakerMappings){this.db.prepare('DELETE FROM meeting_speaker_mappings WHERE meeting_id=?').run(meeting.id);const mapInsert=this.db.prepare('INSERT INTO meeting_speaker_mappings(id,meeting_id,speaker_id,member_id,created_at,updated_at) VALUES(?,?,?,?,?,?)');meeting.speakerMappings.forEach(m=>mapInsert.run(randomUUID(),meeting.id,m.speakerId,m.memberId,now(),now()))}this.db.prepare(`INSERT INTO processing_jobs(id,meeting_id,status,stage,progress,error,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(meeting_id) DO UPDATE SET status=excluded.status,stage=excluded.stage,progress=excluded.progress,error=excluded.error,updated_at=excluded.updated_at`).run(randomUUID(),meeting.id,meeting.status,meeting.stage,meeting.progress,meeting.error,meeting.createdAt,meeting.updatedAt)});txn();return Promise.resolve(meeting)}
 addTasks(tasks:Task[]){const txn=this.db.transaction(()=>tasks.forEach(t=>this.writeTask(t)));txn();return Promise.resolve()}
 saveTask(task:Task){this.writeTask(task);return Promise.resolve(this.hydrateTask(task))}
 saveCandidates(meetingId:string,candidates:TaskCandidate[]){const insert=this.db.prepare('INSERT INTO task_candidates(id,meeting_id,intent,payload_json,created_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET intent=excluded.intent,payload_json=excluded.payload_json,created_at=excluded.created_at');const txn=this.db.transaction(()=>{this.db.prepare('DELETE FROM task_candidates WHERE meeting_id=?').run(meetingId);for(const c of candidates)insert.run(c.id,meetingId,c.intent,JSON.stringify(c.payload),c.createdAt||now())});txn();return Promise.resolve()}
 deleteTask(id:string){this.db.prepare('DELETE FROM tickets WHERE id=?').run(id);return Promise.resolve()}
 getTask(id:string){const row=this.db.prepare('SELECT * FROM tickets WHERE id=?').get(id) as Row|undefined;return Promise.resolve(row?this.taskFromRow(row):null)}
 saveTicket(ticket:Ticket){const stmt=this.db.prepare(`INSERT INTO created_tickets(id,project_id,source_task_id,meeting_id,title,description,context,expected_outcome,task_type,product_surface,component,work_area,priority,assignee,assignee_name,deadline,acceptance_criteria_json,status,created_at,updated_at,source_evidence_json,project_references_json,external_key,provider) VALUES(@id,@projectId,@sourceTaskId,@meetingId,@title,@description,@context,@expectedOutcome,@taskType,@productSurface,@component,@workArea,@priority,@assignee,@assigneeName,@deadline,@acceptanceCriteria,@status,@createdAt,@updatedAt,@sourceEvidence,@projectReferences,@externalKey,@provider) ON CONFLICT(id) DO UPDATE SET title=excluded.title,description=excluded.description,context=excluded.context,expected_outcome=excluded.expected_outcome,task_type=excluded.task_type,product_surface=excluded.product_surface,component=excluded.component,work_area=excluded.work_area,priority=excluded.priority,assignee=excluded.assignee,assignee_name=excluded.assignee_name,deadline=excluded.deadline,acceptance_criteria_json=excluded.acceptance_criteria_json,status=excluded.status,updated_at=excluded.updated_at,source_evidence_json=excluded.source_evidence_json,project_references_json=excluded.project_references_json,external_key=excluded.external_key,provider=excluded.provider`);stmt.run({id:ticket.id,projectId:ticket.projectId,sourceTaskId:ticket.sourceTaskId,meetingId:ticket.meetingId,title:ticket.title,description:ticket.description,context:ticket.context,expectedOutcome:ticket.expectedOutcome,taskType:ticket.taskType,productSurface:ticket.productSurface,component:ticket.component,workArea:ticket.workArea,priority:ticket.priority,assignee:ticket.assignee,assigneeName:ticket.assigneeName,deadline:ticket.deadline,acceptanceCriteria:JSON.stringify(ticket.acceptanceCriteria||[]),status:ticket.status,createdAt:ticket.createdAt,updatedAt:ticket.updatedAt,sourceEvidence:JSON.stringify(ticket.sourceEvidence||[]),projectReferences:JSON.stringify(ticket.projectReferences||[]),externalKey:ticket.externalKey,provider:ticket.provider||'internal'});return Promise.resolve(ticket)}
 getTicket(id:string){const row=this.db.prepare('SELECT * FROM created_tickets WHERE id=?').get(id) as Row|undefined;return Promise.resolve(row?this.ticketFromRow(row):null)}
 findTicketBySourceTaskId(sourceTaskId:string){const row=this.db.prepare('SELECT * FROM created_tickets WHERE source_task_id=?').get(sourceTaskId) as Row|undefined;return Promise.resolve(row?this.ticketFromRow(row):null)}
 listTickets(filter?:{projectId?:string;meetingId?:string;status?:string}){let sql='SELECT * FROM created_tickets WHERE 1=1';const params:unknown[]=[];if(filter?.projectId){sql+=' AND project_id=?';params.push(filter.projectId)}if(filter?.meetingId){sql+=' AND meeting_id=?';params.push(filter.meetingId)}if(filter?.status){sql+=' AND status=?';params.push(filter.status)}sql+=' ORDER BY created_at DESC';const rows=this.db.prepare(sql).all(...params) as Row[];return Promise.resolve(rows.map(r=>this.ticketFromRow(r)))}
 async updateTicket(id:string,patch:UpdateTicketInput){const existing=await this.getTicket(id);if(!existing)throw new Error('Ticket not found.');const updated:Ticket={...existing,...patch,updatedAt:now()};return this.saveTicket(updated)}
 deleteTicket(id:string){this.db.prepare('DELETE FROM created_tickets WHERE id=?').run(id);return Promise.resolve()}
 ticketsForMeeting(meetingId:string){const rows=this.db.prepare('SELECT * FROM created_tickets WHERE meeting_id=? ORDER BY created_at DESC').all(meetingId) as Row[];return rows.map(r=>this.ticketFromRow(r))}

 listProjects(){const rows=this.db.prepare('SELECT * FROM projects WHERE active=1 ORDER BY name COLLATE NOCASE').all() as Row[];return Promise.resolve(rows.map(r=>this.projectFromRow(r,false)))}
 getProject(id:string){const row=this.db.prepare('SELECT * FROM projects WHERE id=? AND active=1').get(id) as Row|undefined;return Promise.resolve(row?this.projectFromRow(row,false):null)}
 saveProject(input:ProjectProfileInput&{id:string;createdAt?:string;updatedAt?:string}){const createdAt=input.createdAt||now(),updatedAt=input.updatedAt||now();const txn=this.db.transaction(()=>this.writeProject({...input,createdAt,updatedAt}));txn();return this.getProject(input.id).then(p=>{if(!p)throw new Error('Project profile could not be reloaded.');return p})}
 deleteProject(id:string){this.db.prepare('UPDATE projects SET active=0,updated_at=? WHERE id=?').run(now(),id);return Promise.resolve()}
 async ingestProjectDocument(projectId:string,filename:string,bytes:Uint8Array){const validated=validateDocumentFilename(filename);if(bytes.byteLength>MAX_DOCUMENT_BYTES)throw new Error(`Document exceeds the ${MAX_DOCUMENT_BYTES/1024/1024} MB upload limit.`);if(!this.db.prepare('SELECT 1 FROM projects WHERE id=? AND active=1').get(projectId))throw new Error('Project profile not found.');const old=this.db.prepare('SELECT * FROM project_documents WHERE project_id=? AND filename=? COLLATE NOCASE').get(projectId,filename) as Row|undefined;const documentId=old?.id||randomUUID(),version=Number(old?.current_version||0)+1,versionId=randomUUID(),uploadedAt=now(),checksum=hash(Buffer.from(bytes));const folder=path.join(this.documentsDir,documentId);mkdirSync(folder,{recursive:true});const originalPath=path.join(folder,`v${version}-${versionId}.${validated.extension}`);const tempPath=`${originalPath}.tmp`;writeFileSync(tempPath,bytes);renameSync(tempPath,originalPath);const insert=this.db.transaction(()=>{if(!old)this.db.prepare(`INSERT INTO project_documents(id,project_id,filename,type,size,uploaded_at,status,current_version,current_version_id,extracted_text_metadata_json,chunk_count,error,active) VALUES(?,?,?,?,? ,?,'uploaded',?,?, '{}',0,NULL,1)`).run(documentId,projectId,filename,validated.type,bytes.byteLength,uploadedAt,version,versionId);else this.db.prepare(`UPDATE project_documents SET type=?,size=?,status='uploaded',current_version=?,current_version_id=?,error=NULL,active=1 WHERE id=?`).run(validated.type,bytes.byteLength,version,versionId,documentId);this.db.prepare('INSERT INTO document_versions(id,document_id,version,file_path,size,checksum,uploaded_at,extracted_text_metadata_json) VALUES(?,?,?,?,?,?,?,?)').run(versionId,documentId,version,originalPath,bytes.byteLength,checksum,uploadedAt,'{}')});insert();return this.processDocument(projectId,documentId,versionId,filename,bytes)}
 async reprocessProjectDocument(projectId:string,documentId:string){const row=this.db.prepare(`SELECT d.filename,v.id version_id,v.file_path FROM project_documents d JOIN document_versions v ON v.id=d.current_version_id WHERE d.project_id=? AND d.id=? AND d.active=1`).get(projectId,documentId) as Row|undefined;if(!row)throw new Error('Project document not found.');this.db.prepare("UPDATE project_documents SET status='processing',error=NULL WHERE id=?").run(documentId);let bytes:Buffer;try{bytes=readFileSync(row.file_path)}catch(error){const message=error instanceof Error?error.message:'Stored source file is unavailable.';this.db.prepare("UPDATE project_documents SET status='failed',chunk_count=0,error=? WHERE id=?").run(`extract: ${message}`,documentId);throw new Error(`Document extraction failed: ${message}`)}return this.processDocument(projectId,documentId,row.version_id,row.filename,bytes)}
 deleteProjectDocument(projectId:string,documentId:string){this.db.prepare('UPDATE project_documents SET active=0 WHERE project_id=? AND id=?').run(projectId,documentId);return Promise.resolve()}
 async searchProjectKnowledge(projectId:string,query:string,limit=8,versionIds?:string[]){const terms=[...new Set((query.toLocaleLowerCase().match(/[\p{L}\p{N}]{2,}/gu)||[]).filter(x=>!['the','and','for','with','from','this','that','into','about','need','should','would','could','there','what','when','where','which'].includes(x)))].slice(0,80);if(!terms.length||versionIds?.length===0)return[];const versionFilter=versionIds?` AND c.version_id IN (${versionIds.map(()=>'?').join(',')})`:'';const rows=this.db.prepare(`SELECT c.* FROM document_chunks c JOIN project_documents d ON d.id=c.document_id AND d.project_id=c.project_id WHERE c.project_id=?${versionIds?'':" AND d.active=1 AND d.status='ready' AND d.current_version_id=c.version_id"}${versionFilter}`).all(projectId,...(versionIds||[])) as Row[];return rows.map(row=>{const text=String(row.text),lower=text.toLocaleLowerCase();const score=terms.reduce((sum,term)=>sum+(lower.split(term).length-1),0)+(terms.filter(term=>String(row.filename).toLocaleLowerCase().includes(term)).length*3);return{row,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.row.filename.localeCompare(b.row.filename)||a.row.chunk_id.localeCompare(b.row.chunk_id)).slice(0,Math.max(1,Math.min(limit,50))).map(({row})=>({projectId:row.project_id,documentId:row.document_id,versionId:row.version_id,filename:row.filename,type:row.type,chunkId:row.chunk_id,text:row.text,pageNumber:row.page_number,rowNumber:row.row_number,rowEndNumber:row.row_end_number,sourceMetadata:json<Record<string,unknown>>(row.source_metadata_json,{})}))}
 async hydrateProjectSnapshot(snapshot:ProjectSnapshot|null){if(!snapshot)return null;const documents=[];for(const doc of snapshot.documents){const indexed=doc.currentVersionId?this.db.prepare('SELECT text FROM document_chunks WHERE project_id=? AND document_id=? AND version_id=? ORDER BY COALESCE(page_number,0),COALESCE(row_number,0),chunk_id').all(snapshot.id,doc.id,doc.currentVersionId) as Row[]:[];const hydrated={...doc,content:indexed.map(x=>x.text).join('\n\n')||doc.content||''};documents.push(hydrated)}return{...snapshot,documents}}
 close(){this.db.close()}

 private projectFromRow(r:Row,withContent:boolean):ProjectProfile{
  const id=r.id;const taskTypes=(this.db.prepare('SELECT id,name,description,position FROM task_types WHERE project_id=? ORDER BY position,name').all(id) as Row[]).map(x=>({id:x.id,name:x.name,description:x.description,position:x.position}));
  const surfaces=(this.db.prepare('SELECT * FROM product_surfaces WHERE project_id=? ORDER BY position,name').all(id) as Row[]).map(x=>({id:x.id,name:x.name,description:x.description,components:(this.db.prepare('SELECT id,name,description FROM surface_components WHERE surface_id=? ORDER BY name').all(x.id) as Row[]).map(c=>({id:c.id,name:c.name,description:c.description}))}));
  const workAreas=(this.db.prepare('SELECT id,name,description FROM work_areas WHERE project_id=? ORDER BY name').all(id) as Row[]).map(x=>({id:x.id,name:x.name,description:x.description}));
  const members=(this.db.prepare('SELECT * FROM project_members WHERE project_id=? ORDER BY name').all(id) as Row[]).map(x=>({id:x.id,name:x.name,role:x.role,skills:json<string[]>(x.skills_json,[]),responsibilities:json<string[]>(x.responsibilities_json,[]),areaIds:json<string[]>(x.area_ids_json,[]),componentIds:json<string[]>(x.component_ids_json,[]),aliases:json<string[]>(x.aliases_json,[]),email:x.email,externalId:x.external_id,active:!!x.active}));
  const assignmentRules=(this.db.prepare('SELECT * FROM assignment_rules WHERE project_id=? ORDER BY position,name').all(id) as Row[]).map(x=>({id:x.id,name:x.name,surfaceId:x.surface_id,componentId:x.component_id,areaId:x.area_id,taskTypeId:x.task_type_id,memberId:x.member_id,active:!!x.active,position:x.position}));
  const docs=(this.db.prepare('SELECT * FROM project_documents WHERE project_id=? AND active=1 ORDER BY uploaded_at').all(id) as Row[]).map(x=>{const versions=(this.db.prepare('SELECT * FROM document_versions WHERE document_id=? ORDER BY version').all(x.id) as Row[]).map(v=>({id:v.id,version:v.version,size:v.size,uploadedAt:v.uploaded_at,checksum:v.checksum,extractedTextMetadata:json<DocumentExtractMetadata>(v.extracted_text_metadata_json,{encoding:'utf-8',characters:0,checksum:null})}));const d:ProjectDocument={id:x.id,projectId:x.project_id,filename:x.filename,type:x.type,size:x.size,uploadedAt:x.uploaded_at,processingStatus:x.status,version:x.current_version,currentVersionId:x.current_version_id,versions,extractedTextMetadata:json<DocumentExtractMetadata>(x.extracted_text_metadata_json,{encoding:'utf-8',characters:0,checksum:null}),chunkCount:x.chunk_count,error:x.error,active:!!x.active};if(withContent&&d.currentVersionId){d.content=(this.db.prepare('SELECT text FROM document_chunks WHERE version_id=? ORDER BY COALESCE(page_number,0),COALESCE(row_number,0),chunk_id').all(d.currentVersionId) as Row[]).map(row=>row.text).join('\n\n')}return d});
  return{id,name:r.name,description:r.description,instructions:r.instructions,glossary:json(r.glossary_json,{}),taskTypes,surfaces,workAreas,members,assignmentRules,documents:docs,createdAt:r.created_at,updatedAt:r.updated_at};
 }
 private writeProject(p:ProjectProfileInput&{id:string;createdAt:string;updatedAt:string}){
  this.db.prepare(`INSERT INTO projects(id,name,description,instructions,glossary_json,created_at,updated_at,active) VALUES(?,?,?,?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,instructions=excluded.instructions,glossary_json=excluded.glossary_json,updated_at=excluded.updated_at,active=1`).run(p.id,p.name,p.description,p.instructions,JSON.stringify(p.glossary),p.createdAt,p.updatedAt);
  for(const table of ['assignment_rules','project_members','product_surfaces','work_areas','task_types'])this.db.prepare(`DELETE FROM ${table} WHERE project_id=?`).run(p.id);
  const addTask=this.db.prepare('INSERT INTO task_types(id,project_id,name,description,position) VALUES(?,?,?,?,?)');p.taskTypes.forEach(x=>addTask.run(x.id,p.id,x.name,x.description,x.position));
  const addSurface=this.db.prepare('INSERT INTO product_surfaces(id,project_id,name,description,position) VALUES(?,?,?,?,?)');const addComponent=this.db.prepare('INSERT INTO surface_components(id,surface_id,name,description) VALUES(?,?,?,?)');p.surfaces.forEach((s,i)=>{addSurface.run(s.id,p.id,s.name,s.description,i);s.components.forEach(c=>addComponent.run(c.id,s.id,c.name,c.description))});
  const addArea=this.db.prepare('INSERT INTO work_areas(id,project_id,name,description) VALUES(?,?,?,?)');p.workAreas.forEach(x=>addArea.run(x.id,p.id,x.name,x.description));
  const addMember=this.db.prepare('INSERT INTO project_members(id,project_id,name,role,skills_json,responsibilities_json,area_ids_json,component_ids_json,aliases_json,email,external_id,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');p.members.forEach(x=>addMember.run(x.id,p.id,x.name,x.role,JSON.stringify(x.skills),JSON.stringify(x.responsibilities),JSON.stringify(x.areaIds),JSON.stringify(x.componentIds),JSON.stringify(x.aliases),x.email,x.externalId,x.active?1:0));
  const addRule=this.db.prepare('INSERT INTO assignment_rules(id,project_id,name,surface_id,component_id,area_id,task_type_id,member_id,active,position) VALUES(?,?,?,?,?,?,?,?,?,?)');p.assignmentRules.forEach(x=>addRule.run(x.id,p.id,x.name,x.surfaceId,x.componentId,x.areaId,x.taskTypeId,x.memberId,x.active?1:0,x.position));
  for(const document of p.documents)this.writeLegacyDocument(p.id,document);
 }
 private writeLegacyDocument(projectId:string,input:{id:string;filename:string;type:string;content?:string}){const content=input.content||'';const existing=this.db.prepare('SELECT * FROM project_documents WHERE id=? AND project_id=?').get(input.id,projectId) as Row|undefined;const checksum=hash(content);if(existing&&existing.current_version_id&&existing.filename===input.filename){const previous=this.db.prepare('SELECT checksum FROM document_versions WHERE id=?').get(existing.current_version_id) as Row|undefined;if(previous?.checksum===checksum)return}const documentId=existing?.id||input.id;const version=Number(existing?.current_version||0)+1,versionId=randomUUID(),uploadedAt=now();const versionDir=path.join(this.documentsDir,documentId);mkdirSync(versionDir,{recursive:true});const target=path.join(versionDir,`v${version}-${versionId}-${path.basename(input.filename).replace(/[^\w.-]/g,'_').slice(0,120)}`);writeFileSync(target,content,'utf8');if(!existing)this.db.prepare("INSERT INTO project_documents(id,project_id,filename,type,size,uploaded_at,status,current_version,current_version_id,extracted_text_metadata_json,chunk_count,error,active) VALUES(?,?,?,?,?,?,'ready',?,?,?,0,NULL,1)").run(documentId,projectId,input.filename,input.type,Buffer.byteLength(content),uploadedAt,version,versionId,JSON.stringify({encoding:'utf-8',characters:content.length,checksum}));else this.db.prepare("UPDATE project_documents SET filename=?,type=?,size=?,status='ready',current_version=?,current_version_id=?,extracted_text_metadata_json=?,chunk_count=0,error=NULL,active=1 WHERE id=?").run(input.filename,input.type,Buffer.byteLength(content),version,versionId,JSON.stringify({encoding:'utf-8',characters:content.length,checksum}),documentId);this.db.prepare('INSERT INTO document_versions(id,document_id,version,file_path,size,checksum,uploaded_at,extracted_text_metadata_json) VALUES(?,?,?,?,?,?,?,?)').run(versionId,documentId,version,target,Buffer.byteLength(content),checksum,uploadedAt,JSON.stringify({encoding:'utf-8',characters:content.length,checksum}))}
 private flagDocumentsNeedingIndexing(){const rows=this.db.prepare("SELECT d.id,v.extracted_text_metadata_json FROM project_documents d JOIN document_versions v ON v.id=d.current_version_id WHERE d.status='ready' AND NOT EXISTS(SELECT 1 FROM document_chunks c WHERE c.version_id=v.id)").all() as Row[];for(const row of rows){const metadata=json<DocumentExtractMetadata>(row.extracted_text_metadata_json,{encoding:'utf-8',characters:0,checksum:null});if(metadata.characters>0)this.db.prepare("UPDATE project_documents SET status='failed',error='index: This document version predates searchable indexing. Reprocess it to build its index.' WHERE id=?").run(row.id)}}
 private async processDocument(projectId:string,documentId:string,versionId:string,filename:string,bytes:Uint8Array){let stage:'extract'|'index'='extract';logger.info('Processing project document',{projectId,documentId,filename,bytes:bytes.byteLength});this.db.prepare("UPDATE project_documents SET status='extracting',error=NULL WHERE id=? AND project_id=?").run(documentId,projectId);try{const extracted=await extractDocument(bytes,filename,projectId,documentId,versionId);stage='index';this.db.prepare("UPDATE project_documents SET status='indexing' WHERE id=? AND project_id=?").run(documentId,projectId);const version=this.db.prepare('SELECT checksum FROM document_versions WHERE id=?').get(versionId) as Row;extracted.metadata.checksum=version.checksum;const txn=this.db.transaction(()=>{this.db.prepare('DELETE FROM document_chunks WHERE version_id=?').run(versionId);const insert=this.db.prepare('INSERT INTO document_chunks(project_id,document_id,version_id,filename,type,chunk_id,text,page_number,row_number,row_end_number,source_metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)');for(const c of extracted.chunks)insert.run(c.projectId,c.documentId,c.versionId,c.filename,c.type,c.chunkId,c.text,c.pageNumber,c.rowNumber,c.rowEndNumber,JSON.stringify(c.sourceMetadata));this.db.prepare('UPDATE document_versions SET extracted_text_metadata_json=? WHERE id=?').run(JSON.stringify(extracted.metadata),versionId);this.db.prepare("UPDATE project_documents SET status='ready',extracted_text_metadata_json=?,chunk_count=?,error=NULL WHERE project_id=? AND id=? AND current_version_id=?").run(JSON.stringify(extracted.metadata),extracted.chunks.length,projectId,documentId,versionId)});txn();logger.info('Document indexed successfully',{projectId,documentId,chunks:extracted.chunks.length});const profileRow=this.db.prepare('SELECT * FROM projects WHERE id=?').get(projectId) as Row;return this.projectFromRow(profileRow,false).documents.find(x=>x.id===documentId)!}catch(error){const message=error instanceof Error?error.message:'Document ingestion failed.';logger.error('Document ingestion failed',{projectId,documentId,stage},error);this.db.prepare("UPDATE project_documents SET status='failed',chunk_count=0,error=? WHERE project_id=? AND id=? AND current_version_id=?").run(`${stage}: ${message}`,projectId,documentId,versionId);throw new Error(`${stage==='extract'?'Document extraction':'Document indexing'} failed: ${message}`)}}
 getSpeakerMappings(meetingId:string):SpeakerMapping[]{const rows=this.db.prepare('SELECT speaker_id,member_id FROM meeting_speaker_mappings WHERE meeting_id=? ORDER BY speaker_id').all(meetingId) as Row[];return rows.map(r=>({speakerId:r.speaker_id,memberId:r.member_id}))}
 setSpeakerMapping(meetingId:string,speakerId:string,memberId:string|null):SpeakerMapping[]{
  if(!speakerId||!speakerId.trim())throw new Error('Speaker ID is required.');
  const meetingRow=this.db.prepare('SELECT project_snapshot_json,project_id FROM meetings WHERE id=?').get(meetingId) as Row|undefined;
  if(!meetingRow)throw new Error('Meeting not found.');
  if(memberId){
   const snapshot=json<ProjectSnapshot|null>(meetingRow.project_snapshot_json,null);
   let member = (snapshot?.members?.find(m=>m.id===memberId) as { id: string; name: string } | undefined);
   if(!member&&meetingRow.project_id){
    member = this.db.prepare('SELECT id,name FROM project_members WHERE project_id=? AND id=?').get(meetingRow.project_id,memberId) as { id: string; name: string } | undefined;
   }
   if(!member)throw new Error('Selected member does not belong to this project.');
   this.db.prepare('INSERT INTO meeting_speaker_mappings(id,meeting_id,speaker_id,member_id,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(meeting_id,speaker_id) DO UPDATE SET member_id=excluded.member_id,updated_at=excluded.updated_at').run(randomUUID(),meetingId,speakerId,memberId,now(),now());
   const displayName=`${member.name} (${speakerId})`;
   this.db.prepare('UPDATE transcript_segments SET speaker=? WHERE meeting_id=? AND (speaker_id=? OR speaker=?)').run(displayName,meetingId,speakerId,speakerId);
  }else{
   this.db.prepare('DELETE FROM meeting_speaker_mappings WHERE meeting_id=? AND speaker_id=?').run(meetingId,speakerId);
   this.db.prepare('UPDATE transcript_segments SET speaker=? WHERE meeting_id=? AND speaker_id=?').run(speakerId,meetingId,speakerId);
  }
  const allMappings=this.getSpeakerMappings(meetingId);
  const mappingsObj:Record<string,string>={};
  for(const m of allMappings)mappingsObj[m.speakerId]=m.memberId;
  this.db.prepare('UPDATE meetings SET speaker_mappings_json=?,updated_at=? WHERE id=?').run(JSON.stringify(mappingsObj),now(),meetingId);
  return allMappings;
 }
 private replaceTranscriptSegments(meeting:Meeting){this.db.prepare('DELETE FROM transcript_segments WHERE meeting_id=?').run(meeting.id);const insert=this.db.prepare('INSERT INTO transcript_segments(id,meeting_id,sequence,start_ms,end_ms,speaker,text,speaker_id,speaker_confidence) VALUES(?,?,?,?,?,?,?,?,?)');const segments=meeting.transcriptSegments&&meeting.transcriptSegments.length?meeting.transcriptSegments:parseTranscript(meeting.transcript||'',meeting.id);segments.forEach((s,idx)=>insert.run(s.id||randomUUID(),meeting.id,s.sequence??idx,s.startMs,s.endMs,s.speaker,s.text,s.speakerId||null,s.speakerConfidence||null))}
 private meetingFromRow(r:Row):Meeting{const segments=(this.db.prepare('SELECT * FROM transcript_segments WHERE meeting_id=? ORDER BY sequence').all(r.id) as Row[]).map(x=>({id:x.id,meetingId:x.meeting_id,sequence:x.sequence,startMs:x.start_ms,endMs:x.end_ms,start:x.start_ms!==null?x.start_ms/1000:null,end:x.end_ms!==null?x.end_ms/1000:null,speaker:x.speaker,speakerId:x.speaker_id||(x.speaker&&/^SPEAKER_\d+$/i.test(x.speaker)?x.speaker:null),speakerConfidence:x.speaker_confidence??null,text:x.text}));const mappings=(this.db.prepare('SELECT speaker_id,member_id FROM meeting_speaker_mappings WHERE meeting_id=? ORDER BY speaker_id').all(r.id) as Row[]).map(m=>({speakerId:m.speaker_id,memberId:m.member_id}));return{id:r.id,inputType:r.input_type,title:r.title,meetingType:r.meeting_type,context:r.context,projectId:r.project_id,projectSnapshot:normalizeSnapshot(json<Row|null>(r.project_snapshot_json,null),r.project_id),originalFileName:r.original_file_name,fileUrl:r.file_url,fileSize:r.file_size,duration:r.duration,status:r.status,stage:r.stage,progress:r.progress,error:r.error,diagnostic:r.diagnostic,transcript:r.transcript,transcriptSegments:segments,summary:r.summary,topics:json(r.topics_json,[]),decisions:json(r.decisions_json,[]),openQuestions:json(r.open_questions_json,[]),diarizationStatus:r.diarization_status||'not_started',diarizationError:r.diarization_error||null,speakerCount:r.speaker_count??null,speakerMappings:mappings.length?mappings:Object.entries(json<Record<string,string>>(r.speaker_mappings_json,{})).map(([k,v])=>({speakerId:k,memberId:v})),createdAt:r.created_at,updatedAt:r.updated_at}}
 private writeTask(task:Task){const meeting=this.db.prepare('SELECT project_id,project_snapshot_json FROM meetings WHERE id=?').get(task.meetingId) as Row|undefined;if(!meeting)throw new Error('Meeting not found.');const snapshot=json<ProjectSnapshot|null>(meeting.project_snapshot_json,null);const projectId=meeting.project_id;const profile=projectId?this.projectFromRow(this.db.prepare('SELECT * FROM projects WHERE id=?').get(projectId) as Row,false):null;
  const taskTypeId=profile?.taskTypes.find(x=>x.name.toLocaleLowerCase()===task.type?.toLocaleLowerCase())?.id||null;const surfaceId=profile?.surfaces.find(x=>x.name.toLocaleLowerCase()===task.surface?.toLocaleLowerCase())?.id||null;const areaId=profile?.workAreas.find(x=>x.name.toLocaleLowerCase()===task.area?.toLocaleLowerCase())?.id||null;const componentId=profile?.surfaces.flatMap(s=>s.components).find(x=>x.name.toLocaleLowerCase()===task.component?.toLocaleLowerCase())?.id||null;const member=task.assignee?profile?.members.find(x=>x.id===task.assignee):undefined;if(task.assignee&&!member)throw new Error('Assignee must be an active project team member.');if(member&&!member.active)throw new Error('Inactive team members cannot be assigned.');
  const stmt=this.db.prepare(`INSERT INTO tickets(id,meeting_id,project_id,title,description,task_type_id,type_label,product_surface_id,work_area_id,component_id,assigned_member_id,priority,status,assignment_source,assignment_needs_review,assignment_reason,rejection_reason,created_ticket_id,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,description=excluded.description,task_type_id=excluded.task_type_id,type_label=excluded.type_label,product_surface_id=excluded.product_surface_id,work_area_id=excluded.work_area_id,component_id=excluded.component_id,assigned_member_id=excluded.assigned_member_id,priority=excluded.priority,status=excluded.status,assignment_source=excluded.assignment_source,assignment_needs_review=excluded.assignment_needs_review,assignment_reason=excluded.assignment_reason,rejection_reason=excluded.rejection_reason,created_ticket_id=excluded.created_ticket_id,payload_json=excluded.payload_json,updated_at=excluded.updated_at`);
  const payload={...task,assignee:member?.id||null,assigneeName:member?.name||null,rejectionReason:task.rejectionReason||null,createdTicketId:task.createdTicketId||null};stmt.run(task.id,task.meetingId,projectId,task.title,task.description,taskTypeId,task.type||'',surfaceId,areaId,componentId,member?.id||null,task.priority||'',task.status,task.assignmentSource||'unassigned',task.assignmentNeedsReview?1:0,task.assignmentReason,task.rejectionReason||null,task.createdTicketId||null,JSON.stringify(payload),task.createdAt,task.updatedAt);
  this.db.prepare('DELETE FROM ticket_document_refs WHERE ticket_id=?').run(task.id);const refInsert=this.db.prepare('INSERT INTO ticket_document_refs(ticket_id,document_version_id,title) VALUES(?,?,?)');for(const id of task.referenceVersionIds||[]){if(!snapshot?.documents.some(d=>d.currentVersionId===id))throw new Error('Ticket references a document version outside its meeting profile snapshot.');const doc=snapshot.documents.find(d=>d.currentVersionId===id)!;refInsert.run(task.id,id,doc.filename)}
 }
 private tasksForMeeting(meetingId:string){
  const rows=(this.db.prepare('SELECT * FROM tickets WHERE meeting_id=? ORDER BY created_at').all(meetingId) as Row[]);
  if(rows.length>0)return rows.map(r=>this.taskFromRow(r));
  const candidateRows=this.db.prepare("SELECT * FROM task_candidates WHERE meeting_id=? AND intent IN ('committed', 'proposed', 'unclear') ORDER BY created_at, id").all(meetingId) as Row[];
  const rescuedTasks:Task[]=[];
  for(const cRow of candidateRows){
   const payload=json<Record<string,unknown>>(cRow.payload_json,{});
   const task=payload.task as Task|undefined;
   if(task&&task.id&&task.title){
    rescuedTasks.push(task);
   }
  }
  if(rescuedTasks.length>0){
   try{
    const txn=this.db.transaction(()=>rescuedTasks.forEach(t=>this.writeTask(t)));
    txn();
    return(this.db.prepare('SELECT * FROM tickets WHERE meeting_id=? ORDER BY created_at').all(meetingId) as Row[]).map(r=>this.taskFromRow(r));
   }catch{
    return rescuedTasks;
   }
  }
  return[];
 }
 private taskFromRow(r:Row):Task{const payload=json<Task>(r.payload_json,{} as Task);const refs=this.db.prepare('SELECT title,document_version_id FROM ticket_document_refs WHERE ticket_id=? ORDER BY title').all(r.id) as Row[];const member=r.assigned_member_id?this.db.prepare('SELECT name FROM project_members WHERE id=?').get(r.assigned_member_id) as Row|undefined:undefined;let status:TaskReviewStatus=(r.status as TaskReviewStatus)||payload.status||'detected';if(status==='draft'){status=(r.assignment_needs_review||payload.assignmentNeedsReview||payload.classificationNeedsReview||(payload.confidence!=null&&payload.confidence<0.75))?'review_required':'detected'}return{...payload,status,rejectionReason:r.rejection_reason??payload.rejectionReason??null,createdTicketId:r.created_ticket_id??payload.createdTicketId??null,assignee:r.assigned_member_id||null,assigneeName:member?.name||payload.assigneeName||null,projectReferences:refs.length?refs.map(x=>x.title):payload.projectReferences||[],referenceVersionIds:refs.length?refs.map(x=>x.document_version_id):payload.referenceVersionIds||[],assignmentSource:r.assignment_source,assignmentNeedsReview:!!r.assignment_needs_review,assignmentReason:r.assignment_reason}}
 private hydrateTask(task:Task){if(!task.assignee)return{...task,assigneeName:null};const row=this.db.prepare('SELECT name FROM project_members WHERE id=?').get(task.assignee) as Row|undefined;return{...task,assigneeName:row?.name||task.assignee}}
 private ticketFromRow(r:Row):Ticket{return{id:r.id,projectId:r.project_id||null,sourceTaskId:r.source_task_id,meetingId:r.meeting_id||null,title:r.title,description:r.description,context:r.context||null,expectedOutcome:r.expected_outcome||null,taskType:r.task_type||null,productSurface:r.product_surface||null,component:r.component||null,workArea:r.work_area||null,priority:(r.priority as Priority)||null,assignee:r.assignee||null,assigneeName:r.assignee_name||null,deadline:r.deadline||null,acceptanceCriteria:json<string[]>(r.acceptance_criteria_json,[]),status:r.status as TicketStatus,createdAt:r.created_at,updatedAt:r.updated_at,sourceEvidence:json<MeetingTaskEvidence[]>(r.source_evidence_json,[]),projectReferences:json<ProjectReferenceEvidence[]>(r.project_references_json,[]),externalKey:r.external_key||null,provider:r.provider||'internal'}}
 private ensureColumn(table:string,column:string,definition:string){try{const columns=this.db.pragma(`table_info(${table})`) as Array<{name:string}>;if(!columns.some(item=>item.name.toLowerCase()===column.toLowerCase()))this.db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`)}catch(e){if(!/duplicate column/i.test(String(e)))throw e}}
 private migrateDocumentStatusCheck(){try{const row=this.db.prepare("SELECT sql FROM sqlite_master WHERE name='project_documents'").get() as {sql?:string}|undefined;if(row?.sql&&!row.sql.includes('extracting')){this.db.pragma('foreign_keys = OFF');this.db.exec(`CREATE TABLE IF NOT EXISTS project_documents_v2 (id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,filename TEXT NOT NULL,type TEXT NOT NULL,size INTEGER NOT NULL,uploaded_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('uploaded','processing','extracting','indexing','ready','failed')),current_version INTEGER NOT NULL,current_version_id TEXT,extracted_text_metadata_json TEXT NOT NULL,chunk_count INTEGER NOT NULL DEFAULT 0,error TEXT,active INTEGER NOT NULL DEFAULT 1,UNIQUE(project_id,filename COLLATE NOCASE));INSERT OR IGNORE INTO project_documents_v2 SELECT * FROM project_documents;DROP TABLE project_documents;ALTER TABLE project_documents_v2 RENAME TO project_documents;CREATE INDEX IF NOT EXISTS idx_documents_project ON project_documents(project_id,active);`);this.db.pragma('foreign_keys = ON')}}catch{try{this.db.pragma('foreign_keys = ON')}catch{/* ignore */}}}
 private migrateLegacyData(){
  const migrate=this.db.transaction(()=>{
   if(this.db.prepare("SELECT 1 FROM storage_meta WHERE key='json_import_v1'").get())return;
   const projectFile=path.join(this.legacyDataDir,'projects.json');
   if(existsSync(projectFile)){const profiles=JSON.parse(readFileSync(projectFile,'utf8')) as Row[];for(const old of profiles)this.migrateLegacyProject(old)}
   const storeFile=path.join(this.legacyDataDir,'store.json');
   if(existsSync(storeFile)){const old=JSON.parse(readFileSync(storeFile,'utf8')) as {meetings?:Row[];tasks?:Row[]};for(const row of old.meetings||[]){const meeting:Meeting={...row,diagnostic:row.diagnostic??null,projectId:row.projectId??null,projectSnapshot:row.projectSnapshot??null,transcriptSegments:[]} as unknown as Meeting;this.saveMeeting(meeting)}for(const row of old.tasks||[]){const hadAssignee=!!row.assignee;const task:Task={...row,assignee:null,surface:row.surface??null,area:row.area??null,component:row.component??null,projectReferences:row.projectReferences??[],referenceVersionIds:[],assigneeName:null,assignmentSource:'unassigned',assignmentNeedsReview:true,assignmentReason:hadAssignee?`Legacy free-text assignee needs team mapping: ${row.assignee}`:'Legacy task assignment needs review.'} as unknown as Task;this.writeTask(task)}}
   this.db.prepare("INSERT INTO storage_meta(key,value) VALUES('json_import_v1','done')").run();
  });
  migrate.immediate();
 }
  private migrateDiarizationSchema(){
   try{
    this.db.exec(`
     CREATE TABLE IF NOT EXISTS meeting_speaker_mappings(
      id TEXT PRIMARY KEY,
      meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
      speaker_id TEXT NOT NULL,
      member_id TEXT NOT NULL,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE(meeting_id,speaker_id)
     );
     CREATE INDEX IF NOT EXISTS idx_speaker_mappings_meeting ON meeting_speaker_mappings(meeting_id);
    `);
   }catch{/* ignore */}
  }
  private migrateLegacyProject(old:Row){const surfaces=(old.platforms||[]).map((name:string)=>({id:randomUUID(),name,description:'',components:[]}));const workAreas=(old.areas||[]).map((name:string)=>({id:randomUUID(),name,description:''}));const docs=(old.documents||[]).map((d:Row)=>({id:d.id||randomUUID(),filename:d.title||'Imported reference.txt',type:'text/plain',content:d.content||''})).filter((x:Row)=>x.content.trim());const input:ProjectProfileInput={name:old.name||'Imported project',description:old.description||'',instructions:old.guidance||old.instructions||'',glossary:{},taskTypes:[{id:randomUUID(),name:'Feature',description:'',position:0},{id:randomUUID(),name:'Bug',description:'',position:1},{id:randomUUID(),name:'Improvement',description:'',position:2},{id:randomUUID(),name:'Technical task',description:'',position:3},{id:randomUUID(),name:'Research',description:'',position:4}],surfaces,workAreas,members:[],assignmentRules:[],documents:docs};this.writeProject({...input,id:old.id||randomUUID(),createdAt:old.createdAt||now(),updatedAt:now()})}
}

export function parseTranscript(transcript:string,meetingId:string):TranscriptSegment[]{const segments=transcript.split(/\n+/).map(line=>line.trim()).filter(Boolean).map((line,sequence)=>{const timed=line.match(/^\[(\d{1,2}):(\d{2})(?:\.(\d{1,3}))?\]\s*(.*)$/);const text=timed?timed[4]:line;const speakerMatch=text.match(/^([^:]{1,80}):\s*(.*)$/);const rawSpeaker=speakerMatch?.[1]?.trim()||null;let speakerId:string|null=null;if(rawSpeaker){const anonMatch=rawSpeaker.match(/\b(SPEAKER_\d+)\b/i);if(anonMatch)speakerId=anonMatch[1].toUpperCase()}const startMs=timed?(Number(timed[1])*60+Number(timed[2]))*1000+Number((timed[3]||'0').padEnd(3,'0')):null;return{id:randomUUID(),meetingId,sequence,startMs,endMs:null as number|null,start:startMs!==null?startMs/1000:null,end:null as number|null,speaker:rawSpeaker,speakerId,speakerConfidence:speakerId?0.9:null,text:speakerMatch?.[2]?.trim()||text}});return segments.map((segment,index)=>{const next=segments[index+1];const endMs=segment.startMs!==null&&next?.startMs!==null&&next?.startMs!==undefined&&next.startMs>segment.startMs?next.startMs:null;return{...segment,endMs,end:endMs!==null?endMs/1000:null}})}
function countChunks(text:string){return text.split(/\n(?=#{1,6}\s)|\n\s*\n/).filter(x=>x.trim()).length}
function stripSnapshotContent(snapshot:ProjectSnapshot):ProjectSnapshot{return{...snapshot,documents:snapshot.documents.map(doc=>{if(!doc.currentVersionId&&doc.content!==undefined)return doc;return Object.fromEntries(Object.entries(doc).filter(([key])=>key!=='content')) as typeof doc})}}
// Compatibility mapper for snapshots written before profile entities had IDs.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function normalizeSnapshot(snapshot:Row|null,projectId:string|null):ProjectSnapshot|null{if(!snapshot)return null;if(snapshot.taskTypes&&snapshot.surfaces&&snapshot.workAreas&&snapshot.members&&snapshot.assignmentRules)return snapshot as unknown as ProjectSnapshot;const id=String(snapshot.id||projectId||randomUUID());const docs=(snapshot.documents||[]).map((d:Row)=>({id:String(d.id||randomUUID()),projectId:id,filename:String(d.filename||d.title||'Imported reference.txt'),type:String(d.type||'text/plain'),size:Number(d.size||Buffer.byteLength(String(d.content||''))),uploadedAt:String(d.uploadedAt||''),processingStatus:'ready' as const,version:Number(d.version||1),currentVersionId:d.currentVersionId||null,versions:d.versions||[],extractedTextMetadata:d.extractedTextMetadata||{encoding:'utf-8',characters:String(d.content||'').length,checksum:null},chunkCount:Number(d.chunkCount||countChunks(String(d.content||''))),error:null,active:true,content:d.content===undefined?undefined:String(d.content)}));return{id,name:String(snapshot.name||'Imported project'),description:String(snapshot.description||''),instructions:String(snapshot.instructions||snapshot.guidance||''),glossary:snapshot.glossary||{},taskTypes:(snapshot.taskTypes||['Feature','Bug','Improvement','Technical task','Research']).map((x:any,i:number)=>typeof x==='string'?{id:randomUUID(),name:x,description:'',position:i}:x),surfaces:(snapshot.surfaces||snapshot.platforms||[]).map((x:any)=>typeof x==='string'?{id:randomUUID(),name:x,description:'',components:[]}:x),workAreas:(snapshot.workAreas||snapshot.areas||[]).map((x:any)=>typeof x==='string'?{id:randomUUID(),name:x,description:''}:x),members:snapshot.members||[],assignmentRules:snapshot.assignmentRules||[],documents:docs}}

const SCHEMA=`
CREATE TABLE IF NOT EXISTS storage_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',instructions TEXT NOT NULL DEFAULT '',glossary_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS task_types(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',position INTEGER NOT NULL DEFAULT 0,UNIQUE(project_id,name COLLATE NOCASE));
CREATE TABLE IF NOT EXISTS product_surfaces(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',position INTEGER NOT NULL DEFAULT 0,UNIQUE(project_id,name COLLATE NOCASE));
CREATE TABLE IF NOT EXISTS surface_components(id TEXT PRIMARY KEY,surface_id TEXT NOT NULL REFERENCES product_surfaces(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',UNIQUE(surface_id,name COLLATE NOCASE));
CREATE TABLE IF NOT EXISTS work_areas(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',UNIQUE(project_id,name COLLATE NOCASE));
CREATE TABLE IF NOT EXISTS project_members(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name TEXT NOT NULL,role TEXT NOT NULL DEFAULT '',skills_json TEXT NOT NULL,responsibilities_json TEXT NOT NULL,area_ids_json TEXT NOT NULL,component_ids_json TEXT NOT NULL,aliases_json TEXT NOT NULL,email TEXT,external_id TEXT,active INTEGER NOT NULL DEFAULT 1,UNIQUE(project_id,name COLLATE NOCASE));
CREATE TABLE IF NOT EXISTS assignment_rules(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name TEXT NOT NULL DEFAULT '',surface_id TEXT REFERENCES product_surfaces(id) ON DELETE SET NULL,component_id TEXT REFERENCES surface_components(id) ON DELETE SET NULL,area_id TEXT REFERENCES work_areas(id) ON DELETE SET NULL,task_type_id TEXT REFERENCES task_types(id) ON DELETE SET NULL,member_id TEXT NOT NULL REFERENCES project_members(id) ON DELETE RESTRICT,active INTEGER NOT NULL DEFAULT 1,position INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS project_documents(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,filename TEXT NOT NULL,type TEXT NOT NULL,size INTEGER NOT NULL,uploaded_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('uploaded','processing','extracting','indexing','ready','failed')),current_version INTEGER NOT NULL,current_version_id TEXT,extracted_text_metadata_json TEXT NOT NULL,chunk_count INTEGER NOT NULL DEFAULT 0,error TEXT,active INTEGER NOT NULL DEFAULT 1,UNIQUE(project_id,filename COLLATE NOCASE));
CREATE TABLE IF NOT EXISTS document_versions(id TEXT PRIMARY KEY,document_id TEXT NOT NULL REFERENCES project_documents(id) ON DELETE CASCADE,version INTEGER NOT NULL,file_path TEXT NOT NULL,size INTEGER NOT NULL,checksum TEXT NOT NULL,uploaded_at TEXT NOT NULL,extracted_text_metadata_json TEXT NOT NULL,UNIQUE(document_id,version));
CREATE TABLE IF NOT EXISTS document_chunks(project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,document_id TEXT NOT NULL REFERENCES project_documents(id) ON DELETE CASCADE,version_id TEXT NOT NULL REFERENCES document_versions(id) ON DELETE CASCADE,filename TEXT NOT NULL,type TEXT NOT NULL,chunk_id TEXT NOT NULL,text TEXT NOT NULL,page_number INTEGER,row_number INTEGER,row_end_number INTEGER,source_metadata_json TEXT NOT NULL,PRIMARY KEY(version_id,chunk_id));
CREATE TABLE IF NOT EXISTS meetings(id TEXT PRIMARY KEY,input_type TEXT NOT NULL,title TEXT NOT NULL,meeting_type TEXT NOT NULL,context TEXT,project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,project_snapshot_json TEXT,original_file_name TEXT NOT NULL,file_url TEXT NOT NULL,file_size INTEGER NOT NULL,duration REAL,status TEXT NOT NULL,stage TEXT,progress INTEGER NOT NULL,error TEXT,diagnostic TEXT,transcript TEXT,summary TEXT,topics_json TEXT NOT NULL,decisions_json TEXT NOT NULL,open_questions_json TEXT NOT NULL DEFAULT '[]',diarization_status TEXT DEFAULT 'not_started',diarization_error TEXT,speaker_count INTEGER,speaker_mappings_json TEXT DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS transcript_segments(id TEXT PRIMARY KEY,meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,sequence INTEGER NOT NULL,start_ms INTEGER,end_ms INTEGER,speaker TEXT,text TEXT NOT NULL,speaker_id TEXT,speaker_confidence REAL,UNIQUE(meeting_id,sequence));
CREATE TABLE IF NOT EXISTS meeting_speaker_mappings(id TEXT PRIMARY KEY,meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,speaker_id TEXT NOT NULL,member_id TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(meeting_id,speaker_id));
CREATE TABLE IF NOT EXISTS task_candidates(id TEXT PRIMARY KEY,meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,intent TEXT NOT NULL,payload_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tickets(id TEXT PRIMARY KEY,meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,title TEXT NOT NULL,description TEXT NOT NULL,task_type_id TEXT REFERENCES task_types(id) ON DELETE SET NULL,type_label TEXT NOT NULL,product_surface_id TEXT REFERENCES product_surfaces(id) ON DELETE SET NULL,work_area_id TEXT REFERENCES work_areas(id) ON DELETE SET NULL,component_id TEXT REFERENCES surface_components(id) ON DELETE SET NULL,assigned_member_id TEXT REFERENCES project_members(id) ON DELETE SET NULL,priority TEXT NOT NULL,status TEXT NOT NULL,assignment_source TEXT NOT NULL,assignment_needs_review INTEGER NOT NULL,assignment_reason TEXT,rejection_reason TEXT,created_ticket_id TEXT,payload_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ticket_document_refs(ticket_id TEXT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,document_version_id TEXT NOT NULL REFERENCES document_versions(id) ON DELETE RESTRICT,title TEXT NOT NULL,PRIMARY KEY(ticket_id,document_version_id));
CREATE TABLE IF NOT EXISTS processing_jobs(id TEXT PRIMARY KEY,meeting_id TEXT NOT NULL UNIQUE REFERENCES meetings(id) ON DELETE CASCADE,status TEXT NOT NULL,stage TEXT,progress INTEGER NOT NULL,error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS created_tickets(id TEXT PRIMARY KEY,project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,source_task_id TEXT NOT NULL,meeting_id TEXT REFERENCES meetings(id) ON DELETE CASCADE,title TEXT NOT NULL,description TEXT NOT NULL,context TEXT,expected_outcome TEXT,task_type TEXT,product_surface TEXT,component TEXT,work_area TEXT,priority TEXT,assignee TEXT,assignee_name TEXT,deadline TEXT,acceptance_criteria_json TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,source_evidence_json TEXT NOT NULL DEFAULT '[]',project_references_json TEXT NOT NULL DEFAULT '[]',external_key TEXT,provider TEXT NOT NULL DEFAULT 'internal');
CREATE INDEX IF NOT EXISTS idx_meetings_created ON meetings(created_at DESC);CREATE INDEX IF NOT EXISTS idx_tickets_meeting ON tickets(meeting_id);CREATE INDEX IF NOT EXISTS idx_documents_project ON project_documents(project_id,active);CREATE INDEX IF NOT EXISTS idx_segments_meeting ON transcript_segments(meeting_id,sequence);CREATE INDEX IF NOT EXISTS idx_speaker_mappings_meeting ON meeting_speaker_mappings(meeting_id);CREATE INDEX IF NOT EXISTS idx_document_chunks_project ON document_chunks(project_id,version_id);CREATE INDEX IF NOT EXISTS idx_document_chunks_source ON document_chunks(document_id,version_id,page_number,row_number);
CREATE UNIQUE INDEX IF NOT EXISTS idx_created_tickets_source_task ON created_tickets(source_task_id);CREATE INDEX IF NOT EXISTS idx_created_tickets_project ON created_tickets(project_id);CREATE INDEX IF NOT EXISTS idx_created_tickets_meeting ON created_tickets(meeting_id);
`;
