import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {SqliteStorage} from './storage';
import {Meeting} from './types';
import {ProjectProfileInput} from './validation';

let root:string;let store:SqliteStorage;
function profileInput():ProjectProfileInput{const areaId=randomUUID(),surfaceId=randomUUID(),componentId=randomUUID(),taskId=randomUUID(),memberId=randomUUID();return{name:'Portal',description:'Client portal',instructions:'Prefer concrete acceptance criteria.',glossary:{SLO:'Service level objective'},taskTypes:[{id:taskId,name:'Feature',description:'New capability',position:0}],surfaces:[{id:surfaceId,name:'Web',description:'Browser app',components:[{id:componentId,name:'Dashboard',description:'Home screen'}]}],workAreas:[{id:areaId,name:'Frontend',description:'Browser UI'}],members:[{id:memberId,name:'Sarah',role:'Frontend engineer',skills:['React'],responsibilities:['Dashboard UI'],areaIds:[areaId],componentIds:[componentId],aliases:['S'],email:null,externalId:'tracker-42',active:true}],assignmentRules:[{id:randomUUID(),name:'Dashboard UI → Sarah',surfaceId,componentId,areaId,taskTypeId:taskId,memberId,active:true,position:0}],documents:[]}}
function meeting(id:string,profile:Awaited<ReturnType<SqliteStorage['getProject']>>):Meeting{if(!profile)throw new Error('Missing project');return{id,inputType:'notes',title:'Planning',meetingType:'Sprint Planning',context:null,projectId:profile.id,projectSnapshot:{id:profile.id,name:profile.name,description:profile.description,instructions:profile.instructions,glossary:profile.glossary,taskTypes:profile.taskTypes,surfaces:profile.surfaces,workAreas:profile.workAreas,members:profile.members,assignmentRules:profile.assignmentRules,documents:profile.documents},originalFileName:'Pasted meeting notes',fileUrl:'',fileSize:0,duration:null,status:'uploaded',stage:null,progress:0,error:null,diagnostic:null,transcript:'[00:12] Sarah: Update the dashboard.',transcriptSegments:[],summary:null,topics:[],decisions:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
beforeEach(async()=>{root=await mkdtemp(path.join(os.tmpdir(),'meeting-foundation-'));store=new SqliteStorage(path.join(root,'app.sqlite'),{dataDir:root,legacyDataDir:path.join(root,'legacy')})});
afterEach(()=>{store.close();return rm(root,{recursive:true,force:true})});
describe('SQLite storage foundation',()=>{
 it('creates a project and persists validated team/configuration entities',async()=>{const input=profileInput();const saved=await store.saveProject({...input,id:randomUUID()});expect(saved.members[0].name).toBe('Sarah');expect(saved.assignmentRules[0].memberId).toBe(saved.members[0].id);expect(saved.taskTypes[0].name).toBe('Feature')});
 it('versions indexed documents without invalidating historical snapshots',async()=>{const input=profileInput();const saved=await store.saveProject({...input,id:randomUUID()});const first=await store.ingestProjectDocument(saved.id,'architecture.md',Buffer.from('# Dashboard\nThe dashboard is a React component in the web client.'));expect(first.processingStatus).toBe('ready');expect(first.version).toBe(1);const project=await store.getProject(saved.id);if(!project)throw new Error('Project missing');const oldMeeting=meeting(randomUUID(),project);oldMeeting.projectSnapshot!.documents=[first];await store.saveMeeting(oldMeeting);const current=await store.ingestProjectDocument(saved.id,'architecture.md',Buffer.from('# Dashboard\nNew version text.'));expect(current.version).toBe(2);const historical=await store.hydrateProjectSnapshot((await store.getMeeting(oldMeeting.id)).meeting?.projectSnapshot||null);expect(historical?.documents[0].content).toContain('React component');expect((await store.searchProjectKnowledge(saved.id,'React component')).length).toBe(0);expect((await store.searchProjectKnowledge(saved.id,'React component',8,[first.currentVersionId!])).length).toBe(1)});
 it('keeps document versions after the current document is removed',async()=>{const input=profileInput();const saved=await store.saveProject({...input,id:randomUUID()});const doc=await store.ingestProjectDocument(saved.id,'architecture.md',Buffer.from('# Dashboard\nReact component details'));const project=await store.getProject(saved.id);if(!project)throw new Error('Project missing');const snapshot=meeting(randomUUID(),project);snapshot.projectSnapshot!.documents=[doc];await store.saveMeeting(snapshot);await store.deleteProjectDocument(saved.id,doc.id);const hydrated=await store.hydrateProjectSnapshot((await store.getMeeting(snapshot.id)).meeting?.projectSnapshot||null);expect(hydrated?.documents[0].content).toContain('Dashboard');expect((await store.getProject(saved.id))?.documents).toHaveLength(0)});
 it('stores timestamped transcript segments alongside the transcript',async()=>{const input=profileInput();const project=await store.saveProject({...input,id:randomUUID()});const m=meeting(randomUUID(),project);await store.saveMeeting(m);const loaded=(await store.getMeeting(m.id)).meeting;expect(loaded?.transcriptSegments[0].startMs).toBe(12000);expect(loaded?.transcriptSegments[0].speaker).toBe('Sarah');expect(loaded?.transcriptSegments[0].text).toBe('Update the dashboard.')});
 it('persists candidate intents separately from generated tickets',async()=>{const input=profileInput();const project=await store.saveProject({...input,id:randomUUID()});const m=meeting(randomUUID(),project);await store.saveMeeting(m);await store.saveCandidates(m.id,[{id:'candidate',meetingId:m.id,intent:'proposed',payload:{title:'Maybe add alerts'},createdAt:new Date().toISOString()}]);expect(store.db.prepare('SELECT intent FROM task_candidates WHERE meeting_id=?').get(m.id)).toEqual({intent:'proposed'})});
 it('indexes searchable CSV rows with source rows and strict project isolation',async()=>{const a=await store.saveProject({...profileInput(),id:randomUUID(),name:'Project A'});const b=await store.saveProject({...profileInput(),id:randomUUID(),name:'Project B'});const doc=await store.ingestProjectDocument(a.id,'team.csv',Buffer.from('name,role,responsibility\nJohn,Backend Developer,Payments API\nSarah,Frontend Developer,Dashboard UI'));await store.ingestProjectDocument(b.id,'secrets.txt',Buffer.from('John owns the confidential satellite subsystem'));const result=await store.searchProjectKnowledge(a.id,'Who is responsible for Payments API?');expect(result).toHaveLength(1);expect(result[0]).toMatchObject({projectId:a.id,documentId:doc.id,versionId:doc.currentVersionId,filename:'team.csv',rowNumber:2});expect(result[0].text).toContain('John');expect(await store.searchProjectKnowledge(b.id,'Payments API')).toHaveLength(0)});
 it('records extraction failure and never marks an invalid PDF ready',async()=>{const project=await store.saveProject({...profileInput(),id:randomUUID()});await expect(store.ingestProjectDocument(project.id,'broken.pdf',Buffer.from('not a PDF'))).rejects.toThrow(/extraction failed/i);const doc=(await store.getProject(project.id))?.documents[0];expect(doc?.processingStatus).toBe('failed');expect(doc?.error).toContain('extract:');expect(doc?.chunkCount).toBe(0)});
 it('records indexing failure and exposes no partially indexed chunks',async()=>{const project=await store.saveProject({...profileInput(),id:randomUUID()});store.db.exec("CREATE TRIGGER reject_document_chunks BEFORE INSERT ON document_chunks BEGIN SELECT RAISE(ABORT, 'index failure'); END;");await expect(store.ingestProjectDocument(project.id,'readme.md',Buffer.from('# Project knowledge\nPayments API handles retries.'))).rejects.toThrow(/indexing failed/i);const doc=(await store.getProject(project.id))?.documents[0];expect(doc?.processingStatus).toBe('failed');expect(doc?.error).toContain('index:');expect(doc?.chunkCount).toBe(0);expect(await store.searchProjectKnowledge(project.id,'Payments API')).toHaveLength(0)});
});
