import {z} from 'zod';

const id=z.string().uuid();
const label=z.string().trim().min(1).max(100);
const unique=(values:string[])=>new Set(values.map(x=>x.trim().toLocaleLowerCase())).size===values.length;
export const meetingContextSchema=z.object({title:z.string().trim().max(160).optional(),meetingType:z.string().trim().max(80).optional(),context:z.string().trim().max(4000).optional(),projectId:id.nullable().optional()});
export const notesSchema=z.string().trim().min(1,'Paste meeting notes to continue.').max(50000,'Meeting notes must be 50,000 characters or fewer.');
const taskTypeSchema=z.object({id,name:label,description:z.string().trim().max(1000).default(''),position:z.number().int().min(0).default(0)});
const componentSchema=z.object({id,name:label,description:z.string().trim().max(1000).default('')});
const surfaceSchema=z.object({id,name:label,description:z.string().trim().max(1000).default(''),components:z.array(componentSchema).max(100)});
const areaSchema=z.object({id,name:label,description:z.string().trim().max(1000).default('')});
const memberSchema=z.object({id,name:label,role:z.string().trim().max(120).default(''),skills:z.array(label).max(50),responsibilities:z.array(label).max(50),areaIds:z.array(id).max(50),componentIds:z.array(id).max(100),aliases:z.array(label).max(30),email:z.string().trim().email().max(254).nullable().optional().default(null),externalId:z.string().trim().max(200).nullable().optional().default(null),active:z.boolean().default(true)});
const ruleSchema=z.object({id,name:z.string().trim().max(160).default(''),surfaceId:id.nullable(),componentId:id.nullable(),areaId:id.nullable(),taskTypeId:id.nullable(),memberId:id,active:z.boolean().default(true),position:z.number().int().min(0).default(0)});
const projectDocumentInputSchema=z.object({id,filename:z.string().trim().min(1).max(255),type:z.string().trim().min(1).max(160).default('text/plain'),content:z.string().trim().min(1).max(30000)});
export const projectProfileInputSchema=z.object({name:label.max(120),description:z.string().trim().max(3000).default(''),instructions:z.string().trim().max(8000).default(''),glossary:z.record(z.string().trim().max(500)).default({}),taskTypes:z.array(taskTypeSchema).min(1).max(30),surfaces:z.array(surfaceSchema).max(30),workAreas:z.array(areaSchema).max(50),members:z.array(memberSchema).max(100),assignmentRules:z.array(ruleSchema).max(200),documents:z.array(projectDocumentInputSchema).max(50)}).superRefine((p,ctx)=>{
 const names:[string,string[]][]=[['taskTypes',p.taskTypes.map(x=>x.name)],['product surfaces',p.surfaces.map(x=>x.name)],['work areas',p.workAreas.map(x=>x.name)],['team member names',p.members.map(x=>x.name)],['document filenames',p.documents.map(x=>x.filename)]];
 for(const [name,values] of names)if(!unique(values))ctx.addIssue({code:'custom',message:`${name} must be unique within this project.`});
 const allIds=[...p.taskTypes.map(x=>x.id),...p.surfaces.map(x=>x.id),...p.surfaces.flatMap(x=>x.components.map(c=>c.id)),...p.workAreas.map(x=>x.id),...p.members.map(x=>x.id),...p.assignmentRules.map(x=>x.id),...p.documents.map(x=>x.id)];if(new Set(allIds).size!==allIds.length)ctx.addIssue({code:'custom',message:'Entity IDs must be unique within a project.'});
 for(const surface of p.surfaces)if(!unique(surface.components.map(x=>x.name)))ctx.addIssue({code:'custom',message:`Components for ${surface.name} must be unique.`});
 const surfaceIds=new Set(p.surfaces.map(x=>x.id)),componentIds=new Set(p.surfaces.flatMap(x=>x.components.map(c=>c.id))),areaIds=new Set(p.workAreas.map(x=>x.id)),taskTypeIds=new Set(p.taskTypes.map(x=>x.id)),memberIds=new Set(p.members.map(x=>x.id));
 for(const m of p.members){if(m.areaIds.some(x=>!areaIds.has(x)))ctx.addIssue({code:'custom',message:`Team member ${m.name} references an unknown work area.`});if(m.componentIds.some(x=>!componentIds.has(x)))ctx.addIssue({code:'custom',message:`Team member ${m.name} references an unknown component.`});if(!unique(m.aliases))ctx.addIssue({code:'custom',message:`Aliases for ${m.name} must be unique.`})}
 for(const r of p.assignmentRules){if(!memberIds.has(r.memberId))ctx.addIssue({code:'custom',message:`Assignment rule ${r.name||r.id} references an unknown member.`});else if(r.active&&!p.members.find(m=>m.id===r.memberId)?.active)ctx.addIssue({code:'custom',message:`Assignment rule ${r.name||r.id} targets an inactive member.`});if(r.surfaceId&&!surfaceIds.has(r.surfaceId))ctx.addIssue({code:'custom',message:`Assignment rule ${r.name||r.id} references an unknown product surface.`});if(r.componentId&&!componentIds.has(r.componentId))ctx.addIssue({code:'custom',message:`Assignment rule ${r.name||r.id} references an unknown component.`});if(r.areaId&&!areaIds.has(r.areaId))ctx.addIssue({code:'custom',message:`Assignment rule ${r.name||r.id} references an unknown work area.`});if(r.taskTypeId&&!taskTypeIds.has(r.taskTypeId))ctx.addIssue({code:'custom',message:`Assignment rule ${r.name||r.id} references an unknown task type.`});if(!r.surfaceId&&!r.componentId&&!r.areaId&&!r.taskTypeId)ctx.addIssue({code:'custom',message:`Assignment rule ${r.name||r.id} needs at least one matching condition.`})}
 const componentSurface=new Map(p.surfaces.flatMap(s=>s.components.map(c=>[c.id,s.id] as const)));
 for(const r of p.assignmentRules)if(r.componentId&&r.surfaceId&&componentSurface.get(r.componentId)!==r.surfaceId)ctx.addIssue({code:'custom',message:`Assignment rule ${r.name||r.id} selects a component outside its product surface.`});
 const docTotal=p.documents.reduce((sum,d)=>sum+d.content.length,0);if(docTotal>500000)ctx.addIssue({code:'custom',message:'Project documents must total 500,000 characters or fewer.'});
});
export type ProjectProfileInput=z.infer<typeof projectProfileInputSchema>;
export function validateTaskProfileReferences(data:Partial<z.infer<typeof taskInputSchema>>,snapshot:import('./types').ProjectSnapshot|null):string|null{
 if(!snapshot)return data.assignee?`An assignee must belong to a selected project's team.`:null;
 if(data.type&&!snapshot.taskTypes.some(x=>x.name.toLocaleLowerCase()===data.type!.toLocaleLowerCase()))return'Choose a task type from the selected project profile.';
 if(data.surface&&!snapshot.surfaces.some(x=>x.name.toLocaleLowerCase()===data.surface!.toLocaleLowerCase()))return'Choose a product surface from the selected project profile.';
 if(data.area&&!snapshot.workAreas.some(x=>x.name.toLocaleLowerCase()===data.area!.toLocaleLowerCase()))return'Choose a work area from the selected project profile.';
 if(data.component&&!snapshot.surfaces.some(s=>s.components.some(x=>x.name.toLocaleLowerCase()===data.component!.toLocaleLowerCase())))return'Choose a component from the selected project profile.';
 if(data.assignee&&!snapshot.members.some(x=>x.id===data.assignee&&x.active))return'Choose an active team member from the selected project profile.';
 if(data.projectReferences?.some(ref=>!snapshot.documents.some(d=>d.filename.toLocaleLowerCase()===ref.toLocaleLowerCase())))return'Ticket references must match a document in the meeting profile snapshot.';
 if(data.referenceVersionIds?.some(id=>!snapshot.documents.some(d=>d.currentVersionId===id)))return'Ticket document versions must belong to the meeting profile snapshot.';
 return null;
}
export const taskInputSchema=z.object({title:z.string().trim().min(1).max(200),description:z.string().trim().max(5000),type:z.string().trim().min(1).max(100).nullable().optional(),surface:z.string().trim().max(100).nullable().optional(),area:z.string().trim().max(100).nullable().optional(),component:z.string().trim().max(100).nullable().optional(),projectReferences:z.array(z.string().trim().max(255)).max(5).optional(),projectReferenceEvidence:z.array(z.object({projectId:id,documentId:id,versionId:id,filename:z.string().max(255),pageNumber:z.number().int().positive().nullable(),rowNumber:z.number().int().positive().nullable(),chunkId:id,excerpt:z.string().max(4000)})).max(20).optional(),referenceVersionIds:z.array(id).max(10).optional(),priority:z.enum(['critical','high','medium','low']).nullable(),assignee:z.string().trim().max(120).nullable().optional(),mentionedPeople:z.array(z.string().max(120)).max(30).optional(),deadline:z.string().trim().max(120).nullable().optional(),deadlineEvidence:z.object({rawPhrase:z.string().max(200),normalizedDate:z.string().date().nullable()}).strict().nullable().optional(),context:z.string().trim().max(2000).optional(),sourceTimestamp:z.string().trim().max(40).nullable().optional(),acceptanceCriteria:z.array(z.string().trim().max(500)).max(20),evidence:z.array(z.object({meetingId:id,segmentId:id,speaker:z.string().nullable(),startMs:z.number().nullable(),endMs:z.number().nullable(),sourceText:z.string().max(10000),quote:z.string().max(2000)})).max(50).optional(),sourceQuote:z.string().trim().max(2000).nullable().optional(),confidence:z.number().min(0).max(1).nullable().optional(),classificationNeedsReview:z.boolean().optional(),classificationReviewReasons:z.array(z.string().max(300)).max(20).optional(),assignmentEvidence:z.enum(['explicit','recommendation','none']).optional(),assignmentSource:z.enum(['meeting','rule','responsibility','skill','component-area','ai-recommendation','manual','unassigned']).optional(),assignmentNeedsReview:z.boolean().optional(),assignmentReason:z.string().trim().max(500).nullable().optional(),status:z.enum(['draft','approved']).optional()});

const candidateIntent=z.enum(['committed','proposed','rejected','cancelled','deferred','unclear']);
const priority=z.enum(['critical','high','medium','low']);
export const taskDraftSchema=z.object({id,meetingId:id,title:z.string().trim().min(1).max(200),description:z.string().trim().min(1).max(5000),taskType:label.nullable(),productSurface:label.nullable(),workArea:label.nullable(),component:label.nullable(),priority:priority.nullable(),assignee:z.string().trim().max(120).nullable(),mentionedPeople:z.array(z.string().trim().min(1).max(120)).max(30),deadline:z.object({rawPhrase:z.string().trim().min(1).max(200),normalizedDate:z.string().date().nullable()}).strict().nullable(),acceptanceCriteria:z.array(z.string().trim().min(1).max(500)).max(20),intent:candidateIntent,confidence:z.number().min(0).max(1),evidence:z.array(z.object({meetingId:id,segmentId:id,speaker:z.string().nullable(),startMs:z.number().int().nonnegative().nullable(),endMs:z.number().int().nonnegative().nullable(),sourceText:z.string().min(1).max(10000),quote:z.string().min(1).max(2000)}).strict()).min(1).max(50),projectReferences:z.array(z.object({projectId:id,documentId:id,versionId:id,filename:z.string().min(1).max(255),pageNumber:z.number().int().positive().nullable(),rowNumber:z.number().int().positive().nullable(),chunkId:id,excerpt:z.string().min(1).max(4000)}).strict()).max(20),assignmentEvidence:z.enum(['explicit','recommendation','none']),needsReview:z.boolean(),reviewReasons:z.array(z.string().max(300)).max(20),priorityEvidence:z.string().max(500).nullable()}).strict();
export type TaskDraftInput=z.infer<typeof taskDraftSchema>;
export const candidateDetectionSchema=z.object({candidates:z.array(z.object({kind:z.enum(['discussion','information','question','status_update','idea','decision','proposal','committed_action']),intent:candidateIntent,summary:z.string().trim().min(1).max(500),evidenceSegmentIds:z.array(id).min(1).max(30),confidence:z.number().min(0).max(1)}).strict()).max(100),topics:z.array(z.string().max(120)).max(30),decisions:z.array(z.object({text:z.string().min(1).max(500),evidenceSegmentIds:z.array(id).min(1).max(20)}).strict()).max(50),openQuestions:z.array(z.object({text:z.string().min(1).max(500),evidenceSegmentIds:z.array(id).min(1).max(20)}).strict()).max(50)}).strict();
export const reconciliationSchema=z.object({summary:z.string().trim().min(1).max(5000),groups:z.array(z.object({candidateIndexes:z.array(z.number().int().nonnegative()).min(1).max(30),kind:z.enum(['discussion','information','question','status_update','idea','decision','proposal','committed_action']),intent:candidateIntent,summary:z.string().trim().min(1).max(500),assignee:z.string().trim().max(120).nullable(),assignmentEvidence:z.enum(['explicit','recommendation','none']),deadlinePhrase:z.string().trim().max(200).nullable(),confidence:z.number().min(0).max(1),mergeRationale:z.string().max(300).nullable()}).strict()).max(100),decisions:z.array(z.object({text:z.string().min(1).max(500),candidateIndexes:z.array(z.number().int().nonnegative()).max(30)}).strict()).max(50),openQuestions:z.array(z.object({text:z.string().min(1).max(500),candidateIndexes:z.array(z.number().int().nonnegative()).max(30)}).strict()).max(50)}).strict();
export const taskDraftOutputSchema=z.object({title:z.string().trim().min(1).max(200),description:z.string().trim().min(1).max(5000),taskType:z.string().trim().max(100).nullable(),productSurface:z.string().trim().max(100).nullable(),workArea:z.string().trim().max(100).nullable(),component:z.string().trim().max(100).nullable(),priority:priority.nullable(),mentionedPeople:z.array(z.string().trim().min(1).max(120)).max(30),deadlinePhrase:z.string().trim().max(200).nullable(),acceptanceCriteria:z.array(z.object({text:z.string().trim().min(1).max(500),evidenceSegmentIds:z.array(id).max(20),projectChunkIds:z.array(id).max(20)}).strict()).max(20),confidence:z.number().min(0).max(1),evidenceQuotes:z.array(z.object({segmentId:id,quote:z.string().min(1).max(2000)}).strict()).min(1).max(50),projectChunkExcerpts:z.array(z.object({chunkId:id,excerpt:z.string().min(1).max(4000)}).strict()).max(20),priorityEvidence:z.object({source:z.enum(['meeting','project','none']),segmentIds:z.array(id).max(10),chunkIds:z.array(id).max(10),explanation:z.string().max(300)}).strict()}).strict();
export const taskDraftBatchSchema=z.object({tasks:z.array(taskDraftOutputSchema.extend({candidateIndex:z.number().int().nonnegative()}).strict()).max(20)}).strict();
const taskCandidateSchema=z.object({intent:z.enum(['committed','proposed','rejected','cancelled','deferred','unclear']),title:z.string().min(1).max(200),description:z.string().max(5000),type:z.string().min(1).max(100),surface:z.string().max(100).nullable().optional().default(null),area:z.string().max(100).nullable().optional().default(null),component:z.string().max(100).nullable().optional().default(null),projectReferences:z.array(z.string().max(255)).max(5).optional().default([]),priority:z.enum(['low','medium','high']),assignee:z.string().nullable(),assignmentEvidence:z.enum(['explicit','recommendation','none']).optional().default('none'),deadline:z.string().nullable().optional().default(null),context:z.string().max(2000).optional().default(''),sourceTimestamp:z.string().nullable().optional().default(null),acceptanceCriteria:z.array(z.string().max(500)).max(20),sourceQuote:z.string().min(1).max(2000),confidence:z.number().min(0).max(1)});
const rawAnalysisSchema=z.object({summary:z.string().min(1).max(5000),topics:z.array(z.string().max(120)).max(20),decisions:z.array(z.string().max(500)).max(30),taskCandidates:z.array(taskCandidateSchema).max(80)});
export const analysisSchema=rawAnalysisSchema.transform(({taskCandidates,...analysis})=>({...analysis,candidates:taskCandidates.map((candidate,index)=>({id:`candidate-${index}`,meetingId:'',intent:candidate.intent,payload:candidate as unknown as Record<string,unknown>,createdAt:''})),tasks:taskCandidates.filter(candidate=>candidate.intent==='committed').map(candidate=>{const task=Object.fromEntries(Object.entries(candidate).filter(([key])=>key!=='intent'));return{...task,referenceVersionIds:[] as string[],assigneeName:null,assignmentSource:'unassigned' as const,assignmentNeedsReview:true,assignmentReason:null} as Omit<typeof candidate,'intent'>&{referenceVersionIds:string[];assigneeName:null;assignmentSource:'unassigned';assignmentNeedsReview:boolean;assignmentReason:null}})}));
