'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {FileAudio,FileText,FileVideo,UploadCloud,X} from 'lucide-react';
import {ProjectProfile} from '@/lib/types';

type InputMode='recording'|'notes';
const formats=['mp3','wav','m4a','mp4','mov','webm','aac'];
export default function NewMeeting(){
 const [mode,setMode]=useState<InputMode>('recording');
 const [file,setFile]=useState<File|null>(null);
 const [projects,setProjects]=useState<ProjectProfile[]>([]);
 const [projectId,setProjectId]=useState('');
 const [drag,setDrag]=useState(false);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const input=useRef<HTMLInputElement>(null);
 const router=useRouter();
 useEffect(()=>{fetch('/api/projects').then(r=>r.json()).then((rows:ProjectProfile[])=>setProjects(rows)).catch(()=>{})},[]);
 function accept(f?:File){setError('');if(!f)return;const ext=f.name.split('.').pop()?.toLowerCase()||'';if(!formats.includes(ext)){setError('Choose an MP3, WAV, M4A, MP4, MOV, WEBM, or AAC recording.');return}if(f.size>100*1024*1024){setError('This file is larger than the 100 MB upload limit.');return}setFile(f)}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(mode==='recording'&&!file){setError('Choose a recording to continue.');return}const form=e.currentTarget;if(mode==='notes'&&!String(new FormData(form).get('notes')||'').trim()){setError('Paste your meeting notes to continue.');return}setBusy(true);setError('');const fd=new FormData(form);fd.set('inputType',mode);if(mode==='recording'&&file)fd.set('file',file);else fd.delete('file');try{const res=await fetch('/api/meetings',{method:'POST',body:fd});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not save this meeting.');const proc=await fetch(`/api/meetings/${data.id}/process`,{method:'POST'});if(!proc.ok)throw new Error((await proc.json()).error||'Could not start processing.');router.push(`/meetings/${data.id}`)}catch(e){setError(e instanceof Error?e.message:'Could not process this meeting.');setBusy(false)}}
 return <div className="page"><div style={{maxWidth:760,margin:'0 auto'}}><div className="eyebrow">NEW MEETING</div><h1 className="page-title">Turn a meeting into clear next steps.</h1><p className="subtle" style={{marginBottom:24}}>Upload a recording or paste notes. Choose a project profile to ground the analysis in its documents and conventions.</p>
  <div className="card" style={{padding:5,display:'flex',gap:5,marginBottom:14}}><button type="button" className={`btn ${mode==='recording'?'btn-primary':''}`} style={{flex:1}} onClick={()=>{setMode('recording');setError('')}}><UploadCloud size={14}/> Recording</button><button type="button" className={`btn ${mode==='notes'?'btn-primary':''}`} style={{flex:1}} onClick={()=>{setMode('notes');setError('')}}><FileText size={14}/> Paste meeting notes</button></div>
  <form onSubmit={submit}><input type="hidden" name="inputType" value={mode}/>
   <div className="card" style={{padding:20,marginBottom:13}}><div className="field"><label htmlFor="project-profile">Project profile <span className="muted">· optional</span></label><select id="project-profile" name="projectId" className="select" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">General meeting · no project profile</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>{projectId?<div className="subtle" style={{fontSize:11}}>The selected project’s guidance, categories, and relevant documents will inform analysis.</div>:!projects.length?<div className="subtle" style={{fontSize:11}}>Create profiles from the Project profiles page.</div>:null}</div>
    {mode==='recording'?<><div className="section-title" style={{marginBottom:13}}>Meeting recording</div><div className={`upload-zone ${drag?'drag':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);accept(e.dataTransfer.files[0])}} onClick={()=>!file&&input.current?.click()} style={{cursor:file?'default':'pointer'}}><input ref={input} type="file" accept={formats.map(x=>`.${x}`).join(',')} hidden onChange={e=>accept(e.target.files?.[0])}/>{file?<><div className="upload-icon">{file.type.startsWith('video')?<FileVideo size={20}/>:<FileAudio size={20}/>}</div><div style={{fontSize:13,fontWeight:600}}>Recording ready</div><div className="subtle" style={{marginTop:5}}>Drop a file here or browse to replace it</div></>:<><div className="upload-icon"><UploadCloud size={20}/></div><div style={{fontSize:14,fontWeight:600}}>Drag & drop meeting audio or video here</div><div className="subtle" style={{margin:'5px 0 13px'}}>MP3, WAV, M4A, MP4, MOV, WEBM, AAC · up to 100 MB</div><button type="button" className="btn btn-sm" onClick={e=>{e.stopPropagation();input.current?.click()}}>Browse files</button></>}</div>{file&&<div className="upload-file"><div className="file-icon">{file.type.startsWith('video')?<FileVideo size={19}/>:<FileAudio size={19}/>}</div><div><div className="file-name">{file.name}</div><div className="file-meta">{(file.size/1024/1024).toFixed(1)} MB · {file.type||file.name.split('.').pop()?.toUpperCase()}</div></div><div className="spacer"/><button type="button" className="btn btn-sm" onClick={()=>setFile(null)} aria-label="Remove file"><X size={14}/></button></div>}</>:<><div className="section-title" style={{marginBottom:7}}>Meeting notes</div><p className="subtle" style={{fontSize:11,margin:'0 0 13px'}}>Paste notes from the meeting. No audio transcription is needed.</p><textarea name="notes" maxLength={50000} className="textarea" style={{minHeight:210}} placeholder={'Paste meeting notes here…\n\nExample:\n- Agreed to add username editing\n- Discussed profile status posts, but deferred the decision'} /></>}</div>
   <div className="card" style={{padding:20}}><div className="section-title" style={{marginBottom:17}}>Meeting details <span className="muted" style={{fontWeight:400}}>· optional</span></div><div className="form-grid"><div className="field"><label>Meeting title</label><input name="title" className="input" maxLength={160} placeholder="e.g. Sprint planning - Payment Service"/></div><div className="field"><label>Meeting type</label><select name="meetingType" className="select"><option>Software Development</option><option>Sprint Planning</option><option>Standup</option><option>Product Meeting</option><option>Client Meeting</option><option>General</option><option>Other</option></select></div></div><div className="field" style={{marginBottom:0}}><label>Additional context <span className="muted" style={{fontWeight:400}}>· optional</span></label><textarea name="context" maxLength={4000} className="textarea" placeholder="Any meeting-specific background that will help interpret the discussion"/></div></div>
   {error&&<div className="error-box" role="alert">{error}</div>}<div className="notice" style={{marginTop:14}}>{mode==='notes'?'Your notes go directly to analysis.':'Your recording is transcribed locally with Whisper small and Vulkan GPU acceleration.'} Meeting analysis uses the selected local model.</div><div style={{display:'flex',justifyContent:'flex-end',marginTop:16}}><button className="btn btn-primary" disabled={busy}>{busy?(mode==='recording'?'Uploading…':'Saving notes…'):(mode==='recording'?'Process recording':'Process notes')}</button></div>
  </form></div></div>
}
